### ISSUE TITLE
alias_generator used instead of field's alias on inheritance

### ISSUE THREAD

**Issue by aljets** [samuelcolvin/pydantic#1177]
# Bug

When `alias` is specified on a field for a class where `alias_generator` is also defined, `alias` is respected for that class but not any derived classes.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```python
             pydantic version: 1.3
            pydantic compiled: False
                 install path: /<snip>/site-packages/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

## Example code

```python
from pydantic import BaseModel, Field


class MyBaseModel(BaseModel):
    class Config:
        alias_generator = lambda x: x.upper()

class MyModel(MyBaseModel):
    my_attribute: bool = Field(..., alias='myATTRIBUTE')

class MyOtherModel(MyModel):
    pass
```

## Examples

```py
>>> MyModel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/site-packages/pydantic/main.py", line 274, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
myATTRIBUTE
  field required (type=value_error.missing)
>>> MyOtherModel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<snip>/site-packages/pydantic/main.py", line 274, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for MyOtherModel
MY_ATTRIBUTE
  field required (type=value_error.missing)
```

Notice that `MyModel` requires `myATTRIBUTE`, as expected, but `MyOtherModel` requires `MY_ATTRIBUTE`, which is from the `alias_generator`

**Comment by samuelcolvin** [comment]
Thanks for reporting, I agree this is wrong, but I'm slightly unclear how best to fix it.

See #1178 for a discussion of a potential solution, your feedback there would be great.
