### ISSUE TITLE
How can i use name "fields" in BaseModel?

### ISSUE THREAD

**Issue by luvwinnie** [samuelcolvin/pydantic#1250]
# Question
Because of my needed for software, i want to use "fields" name in BaseModel.
Is it possible to to use the name of "fields"?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
            pydantic compiled: True
                 install path: /DataStorage/cheesiang_leow/handwritten_recognizer/production/fastapi_prod/venv/lib/python3.6/site-packages/pydantic
               python version: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
                     platform: Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid
     optional deps. installed: []
```

```py
import pydantic
from pydantic import BaseModel

class Model(BaseModel):
    name_1:str
    name_2:str
    fields: List[Dict]

model = Model()
...
```
The code i ran above it shows below's error. 

```
Traceback (most recent call last):
  File "model.py", line 76, in <module>
    class Model(BaseModel):
  File "pydantic/main.py", line 191, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 93, in pydantic.utils.validate_field_name
NameError: Field name "fields" shadows a BaseModel attribute; use a different field name with "alias='fields'".
```
I know if i use other name like Fields is ok, but i want to use lowercase fields.

I don't understand the meaning of use a different field name with "alias='fields'".
Do you have any example with this?

**Comment by samuelcolvin** [comment]
as per [the docs](https://pydantic-docs.helpmanual.io/usage/model_config/)

Use

```py
import pydantic
from pydantic import BaseModel

class Model(BaseModel):
    name_1:str
    name_2:str
    fields_value: List[Dict]

    class Config:
        fields = {'field_value': 'fields'}

```
