### ISSUE TITLE
schema customization

### ISSUE THREAD

**Issue by ysanchezl** [samuelcolvin/pydantic#1285]
Hi!...I try to reproduce the example in pydantic doc about Schema customization: 

`from typing import Dict, Any, Type
from pydantic import BaseModel

class Person(BaseModel):
    name: str
    age: int

    class Config:
        @staticmethod
        def schema_extra(schema: Dict[str, Any], model: Type['Person']) -> None:
            for prop in schema.get('properties', {}).values():
                prop.pop('title', None)

print(Person.schema_json(indent=2))`

and I got this error:

`Traceback (most recent call last):
  File "config_schema.py", line 14, in <module>
    print(Person.schema_json(indent=2))
  File "C:\Users\ysanchel\AppData\Local\Continuum\anaconda3\envs\python365\lib\site-packages\pydantic\main.py", line 526, in schema_json
    return cls.__config__.json_dumps(cls.schema(by_alias=by_alias), default=pydantic_encoder, **dumps_kwargs)
  File "C:\Users\ysanchel\AppData\Local\Continuum\anaconda3\envs\python365\lib\site-packages\pydantic\main.py", line 518, in schema
    s = model_schema(cls, by_alias=by_alias)
  File "C:\Users\ysanchel\AppData\Local\Continuum\anaconda3\envs\python365\lib\site-packages\pydantic\schema.py", line 141, in model_schema
    model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "C:\Users\ysanchel\AppData\Local\Continuum\anaconda3\envs\python365\lib\site-packages\pydantic\schema.py", line 467, in model_process_schema
    schema_extra(s)
TypeError: schema_extra() missing 1 required positional argument: 'model'`

What I am doing wrong?....thxs

**Comment by samuelcolvin** [comment]
Please include in the issue the information requested.

Please format your code so it can be read.
