### ISSUE TITLE
When using `min_items` and `max_items` pydantic cannot accept `None`

### ISSUE THREAD

**Issue by hard-coders** [samuelcolvin/pydantic#1295]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/spike/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Feb 26 2020, 16:45:04)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.3-x86_64-i386-64bit
     optional deps. installed: []

```

```py
>>> class Foo(BaseModel):
...     bar: List = Field(None)
...     baz: List = Field(None, max_items=10)
...
>>> Foo()
Foo(bar=None, baz=None)
>>> Foo(bar=None)
Foo(bar=None, baz=None)
>>> Foo(baz=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spike/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
baz
  value is not a valid list (type=type_error.list)
```

It is not what I expected.

Also when using `min_items`

```py
>>> class Foo(BaseModel):
...     bar: List = Field(None, min_items=0)
...
>>> Foo()
Foo(bar=None)
>>> Foo(bar=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spike/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
bar
  value is not a valid list (type=type_error.list)
```

I think both `min_items` and `max_items` expect that an attribute must iterable. It is the same when using `Optional`.

**Comment by samuelcolvin** [comment]
agreed, thanks for reporting.

PR welcome, otherwise I'll try and fix when I get a chance.

**Comment by PrettyWood** [comment]
When a default value is set I see it working
```python
class Model(BaseModel):
    filter: Pattern = '^regex'
```
by just adding a check like
```python
if field_type is Pattern:  # Pattern is not a class
    f_schema['type'] = 'string'
    f_schema['pattern'] = field.default
    return f_schema, definitions, nested_models
```

Although it would be the exact same thing as
```python
class Model(BaseModel):
    filter: constr(regex='^regex')
```

But without a default value it would probably require some refactoring as the schema generation is based on the class itself and not the instance.
Am I missing something?
