### ISSUE TITLE
`model_name` cannot be used as field name

### ISSUE THREAD

**Issue by kittipatv** [samuelcolvin/pydantic#1366]
# Bug

I'm converting existing dataclasses to use pydantic. When `model_name` is a field in dataclass, pydantic throws

```
Traceback (most recent call last):
  File "test_model_name.py", line 3, in <module>
    @dataclass
  File "pydantic/dataclasses.py", line 146, in pydantic.dataclasses.dataclass
    #
  File "pydantic/dataclasses.py", line 141, in pydantic.dataclasses.dataclass.wrap
    # | True  | True  | True  | add    | raise  | Frozen, so hashable
  File "pydantic/dataclasses.py", line 106, in pydantic.dataclasses._process_class
    #    +--- order= parameter
  File "pydantic/main.py", line 736, in pydantic.main.create_model
TypeError: create_model() got multiple values for keyword argument 'model_name'
```

I think the proper fix would be to make `model_name` in `create_model()` a positional-only parameter. According to my quick code search, the core library seems to be using it that way already. Therefore, this fix should not break any internal API. Is there any concern for external users?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /Users/kittipat/miniconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Minimally reproducible code:

```py
from pydantic.dataclasses import dataclass

@dataclass
class ModelName:
    model_name: str
```

**Comment by kittipatv** [comment]
Positional-only parameters are only supported in python>=3.8. I would propose renaming the argument to `__model_name`
