### ISSUE TITLE
Is it possible to override pydantic typechecking?

### ISSUE THREAD

**Issue by kittipatv** [samuelcolvin/pydantic#1369]
# Question

I have a usecase where dataclass might take proxy object. The proxy object may wrap over the actual object and forward calls to the instance. The use of proxy object includes lazy initialization, add some logging at runtime, etc. Is it possible to tell pydantic to trust that the object has the right type and passes validation? Ideally, I would want to pass a function to override how typecheck works.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /Users/kittipat/miniconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic.dataclasses import dataclass
# Would work with vanilla dataclass
# from dataclasses import dataclass

@dataclass
class A:
    a: int = 1

class LazyProxy:
    def __init__(self, factory):
        self._factory = factory
        self._instance = None

    def __getattr__(self, attr):
        if self._instance is None:
            self._instance = self._factory()
        return getattr(self._instance, attr)

@dataclass
class TestDataclass:
    a: A 


def main():
    print(LazyProxy(A).a)
    d = TestDataclass(a=LazyProxy(A))
    print(d.a.a)

if __name__ == "__main__":
    main()
```

Would now throw error

```
1
Traceback (most recent call last):
  File "test_validator.py", line 30, in <module>
    main()
  File "test_validator.py", line 26, in main
    d = TestDataclass(a=LazyProxy(A))
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 83, in pydantic.dataclasses._process_class._pydantic_post_init
    # +-------+-------+-------+
pydantic.error_wrappers.ValidationError: 1 validation error for TestDataclass
a
  instance of A, tuple or dict expected (type=type_error.dataclass; class_name=A)
```

**Comment by samuelcolvin** [comment]
I think not really possible with dataclasses.

You can achieve this using `.construct()` if you were using a subclass of `BaseModel`.

You might be able to get something to work on a dataclass by hacking the internals before initializing, then reverting after you've created it. But that would be fairly dodgy.
