### ISSUE TITLE
Incorrect signature for instances of models

### ISSUE THREAD

**Issue by JrooTJunior** [samuelcolvin/pydantic#1419]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5
            pydantic compiled: False
                 install path: /home/jrootjunior/.cache/pypoetry/virtualenvs/aiogram-BAWpo_Vh-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr  8 2020, 14:31:25)  [GCC 9.3.0]
                     platform: Linux-5.6.3-arch1-1-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

## Explanation
Feature from #1034 generates incorrect signature for callable instances of models.

### Current behavior
```py
import inspect

from pydantic import BaseModel


class MyModel(BaseModel):
    foo: str

    def __call__(self, bar: str):
        pass


print(inspect.getfullargspec(MyModel))
print(inspect.getfullargspec(MyModel(foo="baz")))
```
will print
```py
FullArgSpec(args=[], varargs=None, varkw=None, defaults=None, kwonlyargs=['foo'], kwonlydefaults=None, annotations={'return': None, 'foo': <class 'str'>})
FullArgSpec(args=[], varargs=None, varkw=None, defaults=None, kwonlyargs=['foo'], kwonlydefaults=None, annotations={'return': None, 'foo': <class 'str'>})
```
Spec for class is correct in most of cases. Is only needed to add `self` to `args`
Spec for instance of that model is incorrect in due to instance can not be called with this spec

### Expected behavior
```py
import inspect


class MyModel:
    def __init__(self, *, foo: str):
        self.foo = foo

    def __call__(self, bar: str):
        pass


print(inspect.getfullargspec(MyModel))
print(inspect.getfullargspec(MyModel(foo="baz")))
```
will print
```py
FullArgSpec(args=['self'], varargs=None, varkw=None, defaults=None, kwonlyargs=['foo'], kwonlydefaults=None, annotations={'foo': <class 'str'>})
FullArgSpec(args=['self', 'bar'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={'bar': <class 'str'>}
```

`getfullargspec` for class returns spec of `__init__`
`getfullargspec` for instance returns spec of `__call__` method

### Another expected behavior
```py
import inspect


class MyModel:
    def __init__(self, *, foo: str):
        self.foo = foo


print(inspect.getfullargspec(MyModel))
print(inspect.getfullargspec(MyModel(foo="baz")))
```
will print
```py
FullArgSpec(args=['self'], varargs=None, varkw=None, defaults=None, kwonlyargs=['foo'], kwonlydefaults=None, annotations={'foo': <class 'str'>})
Traceback (most recent call last):
  File "/usr/lib/python3.8/inspect.py", line 1123, in getfullargspec
    sig = _signature_from_callable(func,
  File "/usr/lib/python3.8/inspect.py", line 2216, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <__main__.MyModel object at 0x7fb1f405b490> is not a callable object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jrootjunior/work/aiogram3/expetiment.py", line 19, in <module>
    print(inspect.getfullargspec(MyModel(foo="baz")))
  File "/usr/lib/python3.8/inspect.py", line 1132, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

`getfullargspec` for class returns spec of `__init__`
`getfullargspec` for instance raises an error about instance is not callable.

**Comment by samuelcolvin** [comment]
thanks for reporting, PR welcome.

**Comment by MrMrRobat** [comment]
Just saw this, ugh. Will make a PR soon :)
