### ISSUE TITLE
Issue with `parse_obj` and `root_validator`

### ISSUE THREAD

**Issue by torfsen** [samuelcolvin/pydantic#1448]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /shared/conda/envs/devl/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Mar 23 2020, 22:36:06)  [GCC 7.3.0]
                     platform: Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
     optional deps. installed: ['typing-extensions']
```

The snippet
```py
from pydantic import BaseModel, root_validator


class Model(BaseModel):
    x: int

    @root_validator
    def validate_x(cls, values):
        print(cls, values)
        assert values['x'] == 1
        return values


if __name__ == '__main__':
    # This works:
    Model(x=1)

    # This fails with KeyError in validate_x
    Model().parse_obj({'x': 1})
```
outputs
```
<class '__main__.Model'> {'x': 1}
<class '__main__.Model'> {}
Traceback (most recent call last):
  File "pydantic_debug.py", line 19, in <module>
    Model().parse_obj({'x': 1})
  File "pydantic/main.py", line 336, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 913, in pydantic.main.validate_model
  File "pydantic_debug.py", line 10, in validate_x
    assert values['x'] == 1
KeyError: 'x'
```
I would have expected that validation would not depend on how I pass the raw data to the model.

**Comment by torfsen** [comment]
And, as always, once you submit the report you notice your own error: In the second case, the call `Model()` already triggers the validation, and since no values are given the shown errors is to be expected. Sorry for the noise.
