### ISSUE TITLE
types.py confuses functools.

### ISSUE THREAD

**Issue by dementedhedgehog** [samuelcolvin/pydantic#151]
I get the following error .. it looks (near the bottom) like functools is trying to import MappingProxyType from types.py.. and it's picking up types.py in pydantic. If so maybe renaming types.py in pydantic is a reasonable work-around for python module-loading wackiness.

```
Error processing line 1 of /usr/local/lib/python3.6/dist-packages/protobuf-3.5.2.post1-py3.6-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 174, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/brhodes/proj/pydantic/pydantic/types.py", line 1, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 122, in <module>
    import enum
  File "/usr/lib/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 561, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 548, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 184, in addpackage
    import traceback
  File "/usr/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.6/linecache.py", line 8, in <module>
    import functools
  File "/usr/lib/python3.6/functools.py", line 22, in <module>
    from types import MappingProxyType
  File "/home/brhodes/proj/pydantic/pydantic/types.py", line 1, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 122, in <module>
    import enum
  File "/usr/lib/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType'
pluto:pydantic$ 
```

**Comment by samuelcolvin** [comment]
Please try to format code in issues properly, it makes it much easier to read and respond. Easiest to just use triple back-quotes around any code block. See [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for more details.

I've edited your example to make it readable.

It looks like the name of `types.py` is causing the problem, but you must be doing something unusual to get this error - I haven't seen it before and no one else has reported it.

Happy to rename `types.py` but first I'd like to understand better (and preferable reproduce) what scenario has caused this issue?

**Comment by samuelcolvin** [comment]
Below is the output from my terminal from starting to investigate this to radon running fine on the code (only the initial install log is truncated for brevity).

I don't get the problem.

Please provide reproducible steps to cause this problem.

```
~ 0  ➤  cd code/pydantic/

pydantic 0  27ms ➤  virtualenv -p `which python3.6` env
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/samuel/code/pydantic/env/bin/python3.6
Also creating executable in /home/samuel/code/pydantic/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

pydantic 0 2.90s ➤  source env/bin/activate

(env) pydantic 0  24ms ➤  make install
pip install -U setuptools pip
Requirement already up-to-date: setuptools in ./env/lib/python3.6/site-packages
Requirement already up-to-date: pip in ./env/lib/python3.6/site-packages
pip install -U -r requirements.txt
Collecting devtools (from -r benchmarks/requirements.txt (line 1))
...install log...
Installing collected packages: devtools, six, python-dateutil, trafaret, pytz, django, djangorestframework, attrs, toastedmarshmallow, docutils, Pygments, pyparsing, packaging, sphinxcontrib-websupport, MarkupSafe, Jinja2, imagesize, snowballstemmer, babel, idna, urllib3, chardet, certifi, requests, alabaster, Sphinx, coverage, pycodestyle, mccabe, pyflakes, flake8, isort, typed-ast, psutil, mypy, py, pluggy, more-itertools, pytest, pytest-cov, apipkg, execnet, pytest-cache, pytest-isort, pytest-mock, termcolor, pytest-sugar, msgpack-python, ujson, dnspython, email-validator
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Pygments-2.2.0 Sphinx-1.7.2 alabaster-0.7.10 apipkg-1.4 attrs-17.4.0 babel-2.5.3 certifi-2018.1.18 chardet-3.0.4 coverage-4.5.1 devtools-0.3 django-2.0.4 djangorestframework-3.8.2 dnspython-1.15.0 docutils-0.14 email-validator-1.0.3 execnet-1.5.0 flake8-3.5.0 idna-2.6 imagesize-1.0.0 isort-4.3.4 mccabe-0.6.1 more-itertools-4.1.0 msgpack-python-0.5.5 mypy-0.560 packaging-17.1 pluggy-0.6.0 psutil-5.4.3 py-1.5.3 pycodestyle-2.3.1 pyflakes-1.6.0 pyparsing-2.2.0 pytest-3.5.0 pytest-cache-1.0 pytest-cov-2.5.1 pytest-isort-0.1.0 pytest-mock-1.7.1 pytest-sugar-0.9.1 python-dateutil-2.7.2 pytz-2018.3 requests-2.18.4 six-1.11.0 snowballstemmer-1.2.1 sphinxcontrib-websupport-1.0.1 termcolor-1.1.0 toastedmarshmallow-0.2.6 trafaret-1.1.1 typed-ast-1.1.0 ujson-1.35 urllib3-1.22
pip install -U .
Processing /home/samuel/code/pydantic
Installing collected packages: pydantic
  Running setup.py install for pydantic ... done
Successfully installed pydantic-0.8.1

(env) pydantic 0 57.87s ➤  deactivate 

pydantic 0  30ms ➤  source env/bin/activate

(env) pydantic 0 115ms ➤  make
pytest --cov=pydantic
Test session starts (platform: linux, Python 3.6.5, pytest 3.5.0, pytest-sugar 0.9.1)
rootdir: /home/samuel/code/pydantic, inifile: setup.cfg
plugins: sugar-0.9.1, mock-1.7.1, isort-0.1.0, cov-2.5.1

 tests/__init__.py ✓                                                                                                                              0%           
 tests/check_tag.py ✓                                                                                                                             1% ▏         
 tests/conftest.py ✓                                                                                                                              1% ▏         
 tests/mypy_test_fails.py ✓                                                                                                                       1% ▎         
 tests/mypy_test_success.py ✓                                                                                                                     1% ▎         
 tests/test_abc.py ✓✓✓                                                                                                                            2% ▎         
 tests/test_complex.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                             15% █▌        
 tests/test_construction.py ✓✓✓✓✓✓✓✓✓✓✓                                                                                                          18% █▉        
 tests/test_create_model.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                         22% ██▎       
 tests/test_datetime_parse.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                           43% ████▍     
 tests/test_main.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                              52% █████▎    
 tests/test_parse.py ✓✓✓✓✓✓✓ss✓✓✓✓✓✓✓✓✓✓                                                                                                         57% █████▊    
 tests/test_settings.py ✓✓✓✓✓✓✓✓✓✓✓                                                                                                              60% ██████▏   
 tests/test_types.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓ss✓✓✓✓✓✓✓✓                                                  82% ████████▎ 
 tests/test_utils.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓s✓✓✓✓✓                                                                                 94% █████████▌
 tests/test_validators.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                  100% ██████████

----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                         Stmts   Miss Branch BrPart     Cover
-----------------------------------------------------------------
pydantic/__init__.py             7      0      0      0   100.00%
pydantic/datetime_parse.py      87      0     46      0   100.00%
pydantic/env_settings.py        34      0      8      0   100.00%
pydantic/exceptions.py          64      0     30      0   100.00%
pydantic/fields.py             218      0    105      0   100.00%
pydantic/main.py               241      0    118      0   100.00%
pydantic/parse.py               51      5     28      1    92.41%
pydantic/types.py              115      4     30      2    95.86%
pydantic/utils.py               58      3     26      1    95.24%
pydantic/validators.py          90      0     42      0   100.00%
pydantic/version.py              3      0      0      0   100.00%
-----------------------------------------------------------------
TOTAL                          968     12    433      4    98.86%


Results (1.39s):
     341 passed
       5 skipped
building coverage html
testing simple example with mypy (and python to check it's sane)...
mypy --ignore-missing-imports --follow-imports=skip --strict-optional tests/mypy_test_success.py
python tests/mypy_test_success.py
checking code with bad type annotations fails...
python tests/mypy_test_fails.py
python setup.py check -rms
running check
flake8 pydantic/ tests/
pytest pydantic -p no:sugar -q
...........                                                                                                                                             [100%]
11 passed in 0.07 seconds

(env) pydantic 0 6.61s ➤  pip install radon
Collecting radon
  Downloading radon-2.2.0-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 298kB/s 
Collecting flake8-polyfill (from radon)
  Downloading flake8_polyfill-1.0.2-py2.py3-none-any.whl
Collecting colorama<0.4,>=0.3 (from radon)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting mando<0.7,>=0.6 (from radon)
  Downloading mando-0.6.4-py2.py3-none-any.whl
Requirement already satisfied: flake8 in ./env/lib/python3.6/site-packages (from flake8-polyfill->radon)
Requirement already satisfied: six in ./env/lib/python3.6/site-packages (from mando<0.7,>=0.6->radon)
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0 in ./env/lib/python3.6/site-packages (from flake8->flake8-polyfill->radon)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./env/lib/python3.6/site-packages (from flake8->flake8-polyfill->radon)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in ./env/lib/python3.6/site-packages (from flake8->flake8-polyfill->radon)
Installing collected packages: flake8-polyfill, colorama, mando, radon
Successfully installed colorama-0.3.9 flake8-polyfill-1.0.2 mando-0.6.4 radon-2.2.0

(env) pydantic 0 3.39s ➤  radon cc pydantic/
pydantic/utils.py
    F 41:0 make_dsn - B
    F 13:0 validate_email - A
    F 94:0 truncate - A
    F 77:0 import_string - A
    F 37:0 _rfc_1738_quote - A
pydantic/types.py
    M 59:4 ConstrainedStr.validate - B
    C 48:0 ConstrainedStr - B
    M 176:4 ConstrainedInt.validate - A
    M 157:4 DSN.validate - A
    C 147:0 DSN - A
    C 167:0 ConstrainedInt - A
    F 119:0 constr - A
    C 36:0 StrictStr - A
    M 41:4 StrictStr.validate - A
    C 80:0 EmailStr - A
    M 81:4 EmailStr.get_validators - A
    M 101:4 NameEmail.get_validators - A
    C 130:0 PyObject - A
    M 138:4 PyObject.validate - A
    F 185:0 conint - A
    M 37:4 StrictStr.get_validators - A
    M 54:4 ConstrainedStr.get_validators - A
    M 89:4 EmailStr.validate - A
    C 94:0 NameEmail - A
    M 97:4 NameEmail.__init__ - A
    M 108:4 NameEmail.validate - A
    M 112:4 NameEmail.__str__ - A
    M 115:4 NameEmail.__repr__ - A
    M 133:4 PyObject.get_validators - A
    M 152:4 DSN.get_validators - A
    M 171:4 ConstrainedInt.get_validators - A
    C 191:0 PositiveInt - A
    C 195:0 NegativeInt - A
pydantic/validators.py
    F 149:0 find_validators - A
    F 25:0 str_validator - A
    F 51:0 bool_validator - A
    F 111:0 uuid_validator - A
    F 67:0 anystr_length_validator - A
    F 79:0 dict_validator - A
    F 19:0 not_none_validator - A
    F 37:0 bytes_validator - A
    F 61:0 number_size_validator - A
    F 73:0 ordered_dict_validator - A
    F 88:0 list_validator - A
    F 94:0 tuple_validator - A
    F 100:0 set_validator - A
    F 106:0 enum_validator - A
    F 15:0 display_as_type - A
pydantic/main.py
    M 254:4 BaseModel._process_values - C
    C 78:0 MetaModel - C
    M 79:4 MetaModel.__new__ - C
    M 220:4 BaseModel.copy - B
    M 291:4 BaseModel._get_value - B
    F 334:0 create_model - B
    M 152:4 BaseModel.__setattr__ - B
    F 31:0 inherit_config - A
    F 64:0 _extract_validators - A
    M 48:4 ValidatorGroup.get_validators - A
    M 55:4 ValidatorGroup.check_for_unused - A
    M 172:4 BaseModel.dict - A
    C 43:0 ValidatorGroup - A
    F 391:0 validator - A
    C 135:0 BaseModel - A
    M 322:4 BaseModel.to_string - A
    M 146:4 BaseModel.__getattr__ - A
    M 181:4 BaseModel.parse_obj - A
    M 188:4 BaseModel.parse_raw - A
    M 306:4 BaseModel.__iter__ - A
    M 313:4 BaseModel.__eq__ - A
    C 17:0 BaseConfig - A
    M 44:4 ValidatorGroup.__init__ - A
    M 143:4 BaseModel.__init__ - A
    M 166:4 BaseModel.__getstate__ - A
    M 169:4 BaseModel.__setstate__ - A
    M 201:4 BaseModel.parse_file - A
    M 210:4 BaseModel.construct - A
    M 241:4 BaseModel.fields - A
    M 245:4 BaseModel.get_validators - A
    M 250:4 BaseModel.validate - A
    M 319:4 BaseModel.__repr__ - A
    M 330:4 BaseModel.__str__ - A
pydantic/fields.py
    M 187:4 Field._populate_validators - C
    M 98:4 Field.prepare - C
    M 131:4 Field._populate_sub_fields - C
    M 212:4 Field.validate - C
    M 252:4 Field._validate_mapping - B
    F 316:0 _get_validator_signature - B
    C 33:0 Field - B
    M 290:4 Field._apply_validators - B
    M 201:4 Field._prep_vals - A
    M 235:4 Field._validate_sequence - A
    M 277:4 Field._validate_singleton - A
    M 72:4 Field.infer - A
    M 87:4 Field.set_config - A
    M 309:4 Field.__str__ - A
    M 40:4 Field.__init__ - A
    F 348:0 _get_field_config - A
    F 355:0 _get_type_origin - A
    C 11:0 ValidatorSignature - A
    C 18:0 Shape - A
    C 25:0 Validator - A
    M 94:4 Field.alt_alias - A
    M 306:4 Field.__repr__ - A
pydantic/env_settings.py
    M 37:4 BaseSettings._substitute_environ - B
    F 12:0 _complex_field - A
    C 20:0 BaseSettings - A
    C 8:0 SettingsError - A
    M 30:4 BaseSettings.__init__ - A
pydantic/parse.py
    F 25:0 load_str_bytes - C
    F 58:0 load_file - A
    C 19:0 Protocol - A
pydantic/exceptions.py
    F 29:0 pretty_errors - B
    F 55:0 _render_errors - B
    F 14:0 type_display - A
    M 75:4 ValidationError.__init__ - A
    M 88:4 ValidationError.display_errors - A
    C 25:0 ErrorDict - A
    C 74:0 ValidationError - A
    M 81:4 ValidationError.json - A
    M 84:4 ValidationError.errors_dict - A
    M 92:4 ValidationError.__str__ - A
    C 96:0 ConfigError - A
    C 100:0 Missing - A
    C 104:0 Extra - A
pydantic/datetime_parse.py
    F 128:0 parse_datetime - C
    F 166:0 parse_duration - C
    F 105:0 parse_time - B
    F 83:0 parse_date - A
    F 63:0 get_numeric - A
    F 76:0 from_unix_seconds - A
    
(env) pydantic 0 309ms ➤  
```

**Comment by samuelcolvin** [comment]
closing this as no response.

If others have a similar problem and can show how `types.py` causes problem in a repeatable way I'm happy to reopen this issue and consider renaming `types.py`
