### ISSUE TITLE
Initialize Data Mapping to Fields

### ISSUE THREAD

**Issue by daniel-butler** [samuelcolvin/pydantic#1603]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
    install path: /usr/local/lib/python3.8/site-packages/pydantic
python version: 3.8.0 (default, Oct 17 2019, 05:36:36)  [GCC 8.3.0]
    platform: Linux-4.19.76-linuxkit-x86_64-with-glibc2.2.5
optional deps. installed: []
```

Keeping this as simple as possible how would I take the `given_outside_data` and convert it into the `OutsideDataModel` below? What I would like to accomplish is for pydantic to handle validating/massaging the outside data for me when I define the schema. 

```py
import pydantic

given_outside_data = {
    '@CreateDate': '2020-05-28T13:43:00.9160714Z',
    'BatchID': 'XXXX-xxxx-xxXX-xx',
    'Items': [...]
}

class OutsideDataModel(pydantic.BaseModel):
    create_datetime: datetime
    batch_id: str
    items: list

OutsideDataModel(**given_outside_data)
```

Using `Config.fields` in the `BaseModel` 

```py
class OutsideDataModel(pydantic.BaseModel):
    create_datetime: datetime
    batch_id: str
    items: list

    class Config:
        fields = {'create_date': '@CreateDate', 'batch_id': 'BatchID', 'items': 'Items'}

```

... or specifying an `alias` in the `Field` parameter.

```py
class ReturnFileFormat(pydantic.BaseModel):
     create_date: datetime = pydantic.Field(alias='@CreateDate')
     batch_id: str = pydantic.Field(alias='BatchID')
     payments: list = pydantic.Field(alias='Payments')

```

... even overwriting the `__init__` method produced the same error.

```py
class ReturnFileFormat(pydantic.BaseModel):
     def __init_(self, response: dict):
         self.create_date = response['@CreateDate']
         self.batch_id = response['BatchID']
         self.payments = response['Payments']
     
     create_date: datetime
     batch_id: str
     payments: list
```

Error Message
```py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for OutsideDataModel
create_date
  field required (type=value_error.missing)
batch_id
  field required (type=value_error.missing)
items
  field required (type=value_error.missing)
```

Because pydantic is saying the field is missing `aliasing` doesn't seem to map in the direction I'm hoping for. The `given_outside_data` could be manipulate to match the pydantic model's fields but if there is a way to handle that within the pydandic model it would be preferred. The `Items` list contains other values that could be modeled with pydantic which is why the self contained option is preferred.

Thank you for all of your work on the library!

**Comment by daniel-butler** [comment]
This method worked for me! I didn't look close enough at the `given_outside_data` to see it didn't match what I was expecting

```py
class OutsideDataModel(pydantic.BaseModel):
    create_datetime: datetime
    batch_id: str
    items: list

    class Config:
        fields = {'create_date': '@CreateDate', 'batch_id': 'BatchID', 'items': 'Items'}
```
