### ISSUE TITLE
Validator is executed open all for List in List field

### ISSUE THREAD

**Issue by cln-m4rie** [samuelcolvin/pydantic#1621]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Apr  9 2020, 18:11:03)  [Clang 11.0.3 (clang-1103.0.32.29)]
                     platform: Darwin-19.5.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

code:
```py
from typing import List

from pydantic import BaseModel, validator

class PositionData(BaseModel):
    positions: List[List[int]]

    @validator("positions", each_item=True)
    def is_quadrangle_positions(cls, v):
        if len(v) != 4:
            raise ValueError("positions list is not quadrangle")
        return v


if __name__ == "__main__":
    test_data = {
        "positions": [
            [0, 0, 3, 3],
            [3, 3, 6, 6],
        ]
    }
    PositionData.parse_obj(test_data)
```
error:
```
Traceback (most recent call last):
  File "/home/admin/pyproj/models.py", line 128, in <module>
    PositionData.parse_obj(test_data)
  File "pydantic/main.py", line 447, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 8 validation errors for PositionData
positions -> 0 -> 0
  object of type 'int' has no len() (type=type_error)
positions -> 0 -> 1
  object of type 'int' has no len() (type=type_error)
positions -> 0 -> 2
  object of type 'int' has no len() (type=type_error)
positions -> 0 -> 3
  object of type 'int' has no len() (type=type_error)
positions -> 1 -> 0
  object of type 'int' has no len() (type=type_error)
positions -> 1 -> 1
  object of type 'int' has no len() (type=type_error)
positions -> 1 -> 2
  object of type 'int' has no len() (type=type_error)
positions -> 1 -> 3
  object of type 'int' has no len() (type=type_error)
```

I'm using this workaroundcode:
```
class PositionData(BaseModel):
    positions: List[List[int]]

    @validator("positions")
    def is_quadrangle_positions(cls, v):
        for item in v:
            if len(item) != 4:
                raise ValueError("positions list is not quadrangle")
        return v
```
But I don't think this is a wise choice.

**Comment by StephenBrown2** [comment]
That's a perfectly fine choice, IMHO. Another option is to make a custom root type, i.e. `Position`, which will give you the ability to do even more with it:

```pycon
from typing import List

from pydantic import BaseModel, validator

class Position(BaseModel):
    __root__: List[int]

	# Note: everything in this class that follows is optional
	# Docs: https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types
    @property
    def x(self):
        return self.__root__[0]

    @property
    def y(self):
        return self.__root__[1]

    @property
    def z(self):
        return self.__root__[2]

    @property
    def t(self):
        return self.__root__[3]

    def __len__(self):
        return len(self.__root__)

    def __iter__(self):
        return iter(self.__root__)

    def __getitem__(self, item):
        return self.__root__[item]

class PositionData(BaseModel):
    positions: List[Position]

    @validator("positions", each_item=True)
    def is_quadrangle_positions(cls, v):
        if isinstance(v, Position):
            if len(v.__root__) != 4:
                raise ValueError("positions list is not quadrangle")
        elif isinstance(v, list):
            if len(v) != 4:
                raise ValueError("positions list is not quadrangle")
        else:
            raise ValueError("positions is not a list")
        return v


test_data = {
    "positions": [
        [0, 0, 3, 3],
        [3, 3, 6, 6],
    ]
}

data = PositionData.parse_obj(test_data)

data
> PositionData(positions=[Position(__root__=[0, 0, 3, 3]), Position(__root__=[3, 3, 6, 6])])
data.positions[0].z
> 3
```

**Comment by cln-m4rie** [comment]
@StephenBrown2 
Thank you.
I'll try it.
