### ISSUE TITLE
Nested color object is not converted to json

### ISSUE THREAD

**Issue by fortunto2** [samuelcolvin/pydantic#1636]
# Bug

I collect an object, a list of dominant colors. 
And then I’m going to save the Django 2 in the jsonfield(postgres).

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
     pydantic compiled: True
     python version: 3.7.3 (default, Oct  7 2019, 12:56:13)  [GCC 8.3.0]
     platform: Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco
     optional deps. installed: ['typing-extensions']
...
```

```py

from pydantic.color import Color

class DominantColor(BaseModel):
    percent: int = Field(ge=0, le=100, default=None)
    color: Color

    @property
    def rgb(self):
        return self.color.as_rgb_tuple()

    @property
    def name(self):
        return self.color.as_named()

class DominantColorList(BaseModel):
    __root__: List[DominantColor]

class Features(BaseModel):
    score: float = None
    dom_colors: List[DominantColor] = []


class Frame(BaseEntity):
    ss: int = Field(ge=0)
    features: Features = {}

class FramesList(BaseEntity):
    __root__: List[Frame]

get_features(frame_array):

  ...

  dom_colors = [
            {
                'color': (0,0,100),
                'percent': 10
            },
            {
                'color': (0,100,100),
                'percent': 20
            },
            {
                'color': (100,0,100),
                'percent': 30
            },
        ]

        # from pydantic import parse_obj_as
        # dom_colors = parse_obj_as(List[DominantColor], dom_colors)

        dom_colors = DominantColorList.parse_obj(dom_colors)

        _dict = {
            "score":1
            "dom_colors": dom_colors.dict()['__root__'],
        }

        features = Features(**_dict)

       return features

frames: List[Frame] = []
frames_array: List[numpy] = []

for i, frame_array in enumerate(frames_array):

       features = get_features(frame_array)

        frame = Frame(
            ss=key_frames[i],
            features=features
        )

        frames.append(frame)

#Django
model.jsonfiled = FramesList.parse_obj(frames).dict()['__root__']
model.save()
```
get  
```
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "//venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "//venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "//venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "//venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "//backend/apps/files/management/commands/file.py", line 36, in handle
    file.start_processing()
  File "//venv/lib/python3.7/site-packages/django_fsm/__init__.py", line 520, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
  File "//venv/lib/python3.7/site-packages/django_fsm/__init__.py", line 326, in change_state
    result = method(instance, *args, **kwargs)
  File "//backend/apps/files/states.py", line 76, in start_processing
    self.ai_base()
  File "//venv/lib/python3.7/site-packages/django_fsm/__init__.py", line 520, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
  File "//venv/lib/python3.7/site-packages/django_fsm/__init__.py", line 326, in change_state
    result = method(instance, *args, **kwargs)
  File "//backend/apps/files/states.py", line 150, in ai_base
    res = task_ai_base(self.pk)
  File "//backend/apps/files/tasks/ai_base.py", line 160, in task_ai_base
    video_data.save()
  File "//venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "//venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "//venv/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "//venv/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "//venv/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "//venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "//venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "//venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "//venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "//venv/lib/python3.7/site-packages/psycopg2/_json.py", line 78, in getquoted
    s = self.dumps(self.adapted)
  File "//venv/lib/python3.7/site-packages/django/contrib/postgres/fields/jsonb.py", line 27, in dumps
    return json.dumps(obj, **options)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Color is not JSON serializable

```

try
```
    for frame in frames:
        for color in frame.features.dom_colors:
            frame.features.dom_colors = [c.color.dict() for c in frame.features.dom_colors]
```

get
```
  File "//backend/apps/files/tasks/ai_base.py", line 156, in task_ai_base
    frame.features.dom_colors = [c.color.dict() for c in frame.features.dom_colors]
  File "//backend/apps/files/tasks/ai_base.py", line 156, in <listcomp>
    frame.features.dom_colors = [c.color.dict() for c in frame.features.dom_colors]
AttributeError: 'Color' object has no attribute 'dict'
```
what am I doing wrong?)
Thats work very well...
```
class DominantColor(BaseEntity):
    percent: int = Field(ge=0, le=100, default=None)
    color: Tuple[int, int, int]
```

and how best way to create FramesList and SegmentsList? without ugly __root__?
```
    video_data.frames = FramesList.parse_obj(frames).dict()['__root__']
    video_data.save()
```

**Comment by samuelcolvin** [comment]
I don't see a bug in pydantic here. If you're sure there's a problem with pydantic, please create a short self contained example of the problem.

**Comment by fortunto2** [comment]
I fix it https://gist.github.com/fortunto2/b4379b2dc6ebc9b0228539b9a8d96c6c
Create custom Encoder for json
