### ISSUE TITLE
Make hypothesis + pydantic work

### ISSUE THREAD

**Issue by MartinThoma** [samuelcolvin/pydantic#1666]
# Feature Request
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/moose/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, May 14 2020, 22:06:53)  [GCC 9.3.0]
                     platform: Linux-5.4.0-39-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

First of all: Awesome project! I like pydantic a lot, thank you for putting the effort in it :-)

[hypothesis](https://github.com/HypothesisWorks/hypothesis) is a property testing framework. It generates input for the test data and helps to generate atypical inputs, e.g. for integers it could generate positive, negative, zero, int32 boundaries. This way, it keeps the test code clean and you don't forget important special cases.

It would be pretty awesome if the following would work. It should automatically generate "Person" objects:

```python
from typing import Optional

from hypothesis import given
from hypothesis.strategies import from_type
from pydantic import BaseModel


class Adress(BaseModel):
    city: str
    street: str
    house_number: int
    postal_code: int


class Person(BaseModel):
    prename: str
    middlename: Optional[str]
    lastname: str
    address: Adress


@given(from_type(Person))
def test_me(person: Person):
    assert isinstance(person, Person)
```

Aparently, pydantic does not generate correctly typed `__init__` methods ([source](https://stackoverflow.com/a/62593144/562769)). Maybe this can be fixed?

**Comment by samuelcolvin** [comment]
pydantic generates the correct signature for for models, to help in cases exactly like this, see #1034.

Also see timothycrosley/hypothesis-auto#10 - since signatures are generated for models in pydantic v1.5, and [`__signature__` is interpret by hypothesis `>5.8.3`](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-8-3) this should in theory work.

Need more details on the error to investigate.

note: the template for issues is there for a reason, if you'd included it I would be able to know what version of pydantic you're using which might explain the problem. Please fill it in.

**Comment by MartinThoma** [comment]
I've added the pydantic version on the top.

```
$ pip freeze | grep -i hypothesis
hypothesis==5.18.3
```

**Comment by MartinThoma** [comment]
Huh. Strange. Now it works ... as I can't reproduce the issue, I'm closing this. Sorry for the confusion. And awesome that it works :tada:

**Comment by samuelcolvin** [comment]
great. Maybe you could comment on the stackoverflow issue explaining that it works.

**Comment by Kludex** [comment]
For future reference, Hypothesis plugin released on [Pydantic 1.8](https://pydantic-docs.helpmanual.io/changelog/#v18-2021-02-26).

Reference: https://pydantic-docs.helpmanual.io/hypothesis_plugin/

**Comment by sidmitra** [comment]
I'm still seeing the following error with
- `python==3.9.4`
- `pydantic==1.8.1` 
- `hypothesis==6.10.0` 

```python
Traceback (most recent call last):
  File "/tmp/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/tmp/venv/lib/python3.9/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/venv/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/entry_points.py", line 62, in run
    hook = entry.load()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1116, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "pydantic/_hypothesis_plugin.py", line 362, in init pydantic._hypothesis_plugin
  File "pydantic/_hypothesis_plugin.py", line 196, in pydantic._hypothesis_plugin._registered
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/core.py", line 1719, in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/strategies.py", line 134, in accept
    recur(self)
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/strategies.py", line 130, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py", line 92, in calc_is_empty
    return recur(self.wrapped_strategy)
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py", line 112, in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
  File "/tmp/venv/lib/python3.9/site-packages/hypothesis/strategies/_internal/numbers.py", line 374, in floats
    assert max_value < max_arg  # type: ignore
AssertionError: assert -0.0 < 0
Error: Process completed with exit code 1.
```

**Comment by nocko** [comment]
@sidmitra I was receiving a similar error (again, only on gitlab-runner). It seems to be related to coverage.py. I found that by using pytest-cov I was able to run the tests (with coverage) successfully:

Initial failure:
``` bash
coverage run --concurrency=gevent --source=<path> -m pytest --junitxml=tests.xml tests
```

Working:
``` bash
pip install pytest-cov
`python` -m pytest --cov=c3loc tests  # Options now specified in .coveragerc
```

**Comment by ento** [comment]
>    assert max_value < max_arg  # type: ignore  
> AssertionError: assert -0.0 < 0  

If gevent was part of the project's dependencies, this error will likely be fixed by https://github.com/gevent/gevent/pull/1864

In the case of coverage.py, too, `--concurrency=gevent` might've been what was causing the error.
