### ISSUE TITLE
BaseModel.json() does not use Config.json_encoders from nested models' config

### ISSUE THREAD

**Issue by mdgilene** [samuelcolvin/pydantic#1699]
# Bug
When serializing a model, jsonable_encoder does not appear to take custom json_encoders from nested models into account.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: D:\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
                     platform: Windows-10-10.0.17134-SP0
     optional deps. installed: []
```

```py
from datetime import datetime
from typing import List

from bson.objectid import InvalidId, ObjectId
from pydantic import BaseConfig, BaseModel


class OID(str):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        try:
            return ObjectId(str(v))
        except InvalidId:
            raise ValueError("Not a valid ObjectId")


class MongoModel(BaseModel):
    class Config(BaseConfig):
        allow_population_by_field_name = True
        json_encoders = {
            datetime: lambda dt: dt.isoformat(),
            ObjectId: lambda oid: str(oid)
        }

    @classmethod
    def from_mongo(cls, data: dict):
        """We must convert _id into "id". """
        if not data:
            return data
        id = data.pop('_id', None)
        return cls(**dict(data, id=id))

    def mongo(self, **kwargs):
        exclude_unset = kwargs.pop('exclude_unset', True)
        by_alias = kwargs.pop('by_alias', True)

        parsed = self.dict(
            exclude_unset=exclude_unset,
            by_alias=by_alias,
            **kwargs,
        )

        # Mongo uses `_id` as default key. We should stick to that as well.
        if '_id' not in parsed and 'id' in parsed:
            parsed['_id'] = parsed.pop('id')

        return parsed


class User(MongoModel):
    id: OID


class UserList(BaseModel):
    users: List[User]


user = User(id=ObjectId())
userList = UserList(users=[user])

print(user.json())
print(userList.json())
```

## Output
```
{"id": "5f0717ec4bc9d3fdd059ddb0"}
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    print('User List', userList.json())
  File "pydantic\main.py", line 433, in pydantic.main.BaseModel.json
  File "C:\Anaconda3_2019.10\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Anaconda3_2019.10\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Anaconda3_2019.10\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic\json.py", line 62, in pydantic.json.pydantic_encoder
TypeError: Object of type 'ObjectId' is not JSON serializable
```

**Comment by PrettyWood** [comment]
Hello @mdgilene 
It's not a bug it's just that for `User` you use `MongoModel` but for `UserList` you use `BaseModel`
If you use `MongoModel` for both it works

**Comment by mdgilene** [comment]
I understand that that is a potential solution, however in my opinion it seems a bit hacky to have to have every one of my models extend that base class even if it isn't directly in need of the custom encoders.

For example, what if I wanted to use a GenericModel

```
from typing import Generic, List, TypeVar

from pydantic.generics import GenericModel

ModelType = TypeVar('ModelType')


class GenericList(GenericModel, Generic[ModelType]):
    contents: List[ModelType]

model_list = GenericList[User](contents=[user])
```

Same issue occurs here. This generic model should't need to extend my MongoModel base class.

**Comment by samuelcolvin** [comment]
This is not a bug, it could be a feature request, but I don't think it makes sense and it would likely damage performance a lot.
