### ISSUE TITLE
Error in find_validators (issubclass() arg 1 must be a class)

### ISSUE THREAD

**Issue by jbeezley** [samuelcolvin/pydantic#1722]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6
            pydantic compiled: True
                 install path: <prefix>/env/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
                     platform: Linux-5.4.0-39-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

```py
from typing import List

from pydantic import BaseModel, Field, validator


class Schema(BaseModel):
    foo: List[str] = Field(default_factory=list)

    @validator("foo", pre=True, each_item=True)
    def mutate_foo(cls, v):
        return f"{v}-1"


class Derived(Schema):
    pass


print(Derived(foo=['bar']).foo)
```

This results in
```
Traceback (most recent call last):
  File "pydantic/validators.py", line 579, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ptest.py", line 14, in <module>
    class Derived(Schema):
  File "pydantic/main.py", line 231, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 523, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 588, in find_validators
RuntimeError: error checking inheritance of typing.List[str] (type: List[str])
```

This code sample works in pydantic 1.5.1.  The bug seems to rely on the combination of `default_factory`, the `@validator` method, and the subclass.  Removing any one of these causes the code to run correctly.

Note: there are a few other issues with the similar error message, but they appear to be distinct from this because they apply to versions <= 1.5.1 and have slightly different stack traces.

**Comment by PrettyWood** [comment]
Hello @jbeezley 
There is already a fix on `default_factory` https://github.com/samuelcolvin/pydantic/pull/1712, which seems to fix your issue as well (instead of the error you get `['bar-1']` as expected).
@samuelcolvin will probably ship a patched version 1.6.1 soon if the fix is approved
