### ISSUE TITLE
Naming of validator functions when using self-referencing models

### ISSUE THREAD

**Issue by khalo-sa** [samuelcolvin/pydantic#1746]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/USER/Dev/pyenv/py38/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
                     platform: Linux-5.4.0-7634-generic-x86_64-with-glibc2.29
     optional deps. installed: []

```

The following code throws an exception. However, if I change the validator function's name from "validate" to anything else, it works. I assume that "validate" is used in Pydantic's source code, but I couldn't find any comment in the [validator's section of the docs](https://pydantic-docs.helpmanual.io/usage/validators/) about forbidden validator names.

```py
from pydantic import BaseModel, validator
from typing import List


class Foo(BaseModel):
    name: str

    @validator('name')
    def validate(cls, v):
        allowed = ["a", "b"]
        if v not in allowed:
            raise ValueError(f"Value {v} is not allowed")
        return v

    #: The sibling of `Foo` is referenced by string
    siblings: List["Foo"] = None


Foo.update_forward_refs()

print(Foo(name="a"))
print(Foo(name="a", siblings=[Foo(name="a"), Foo(name="b")]))

"""
returns:
#> name='a' sibling=None
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    print(Foo(name="a", sibling=Foo(name="b")))
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
sibling
  Value 'name='b' sibling=None' is not allowed (type=value_error)
"""

```

**Comment by samuelcolvin** [comment]
Yes, `validate` as a public method was a mistake, it will be removed in v2.

Hopefully other public methods will also be changed in v2, see #1001.
