### ISSUE TITLE
How can I correctly validate a list of dictionaries?

### ISSUE THREAD

**Issue by eceppda** [samuelcolvin/pydantic#1843]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
| => python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.4
            pydantic compiled: False
                 install path: [...]/venv/lib/python3.6/site-packages/pydantic
               python version: 3.6.2 (default, Jan 16 2020, 10:16:00)  [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)]
                     platform: Darwin-19.5.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I have a function that returns a list of dictionaries, and want the output of the function to be passed as a parameter to a pydantic model. I didn't expect either example below to fail validation, and I'm unclear why validation is failing and what I can do to correct it. 

```py
>>> from pydantic import BaseModel
>>> class ModelA(BaseModel):
...     a: List[Dict]
...     
>>>ModelA(a=list({"a": "b"}))
... 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "[...]/venv/lib/python3.6/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ModelA
a -> 0
  value is not a valid dict (type=type_error.dict)
```

```py
>>> from pydantic import BaseModel
>>> class ModelB(BaseModel):
...     b: List[Dict[str, str]]]
...     
>>>ModelB(b=list({"b":"c"}))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "[...]/venv/lib/python3.6/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ModelB
b -> 0
  value is not a valid dict (type=type_error.dict)
```

**Comment by PrettyWood** [comment]
Hello @eceppda 
It's because of `python` ;)

```python
a = list({"a": "b"})
print(a)
# ['a']
```

Just use instead `[]` like `ModelA(a=[{"a": "b"}])` and you should be good
