### ISSUE TITLE
Protocols are not supported

### ISSUE THREAD

**Issue by signalpillar** [samuelcolvin/pydantic#185]
## Case 1

```
import typing as t
from pydantic import BaseModel


class Test(BaseModel):

    mapping: t.Mapping
```

For mapping we get the following error

```
{10:40}/tmp ➭ python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    class Test(BaseModel):
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/main.py", line 116, in __new__
    config=config,
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 84, in infer
    description=field_config and field_config.get('description'),
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 70, in __init__
    self.prepare()
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 113, in prepare
    self._populate_validators()
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 192, in _populate_validators
    *(get_validators() if get_validators else find_validators(self.type_)),
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/validators.py", line 204, in find_validators
    raise ConfigError(f'no validator found for {type_}')
pydantic.exceptions.ConfigError: no validator found for typing.Mapping
```

## Case 2

Another interesting case with the `Sequence` that is parameterised with type.

```
import typing as t
from pydantic import BaseModel


class MyModel:
    pass


class Test(BaseModel):

    seq: t.Sequence[MyModel]
```

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    class Test(BaseModel):
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/main.py", line 116, in __new__
    config=config,
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 84, in infer
    description=field_config and field_config.get('description'),
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 70, in __init__
    self.prepare()
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 112, in prepare
    self._populate_sub_fields()
  File "/tmp/.tox/test_service/lib/python3.6/site-packages/pydantic/fields.py", line 161, in _populate_sub_fields
    assert issubclass(origin, Mapping)
AssertionError
```

**Comment by samuelcolvin** [comment]
Type checking is already extremely complex, I really don't want to add this unless it's absolutely necessary.

Do you really need this or can you get away with using `Dict`, `List` and `Set` instead?

**Comment by signalpillar** [comment]
Ah, I see. Yes, I am using now those concrete types as not many models are touched.
Your project is really cool so I thought that I could improve it at least letting you know about other use cases.

That is one of the best practices in our projects to use the protocols instead of the concrete implementations. (sequence/iterable vs tuple/list and mapping vs dict). `Sequence` and `Mapping` are quite popular and basic types.

Thank you.
