### ISSUE TITLE
Generic List not supports validators

### ISSUE THREAD

**Issue by profx5** [samuelcolvin/pydantic#1852]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: False
               python version: 3.8.5 (default, Aug 19 2020, 20:48:48)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Hi. I am experimenting with Generic fields (as described [here](https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types)).
Got some problem with calling validator on `List[T]` instead of `Generic[T]`:
```py
from typing import List, Any, TypeVar, Generic
from pydantic import BaseModel
from pydantic.fields import ModelField


T = TypeVar("CommaSeparetedType")


class SomeGeneric(Generic[T]):
    @classmethod
    def __get_validators__(cls) -> Any:
        yield cls.validate

    @classmethod
    def validate(cls, v: Any, field: ModelField) -> Any:
        raise ValueError("some generic error")
        return v


class SomeList(List[T]):
    @classmethod
    def __get_validators__(cls) -> Any:
        yield cls.validate

    @classmethod
    def validate(cls, v: Any, field: ModelField) -> Any:
        raise ValueError("some list error")
        return v


class TestModel(BaseModel):
    generic_field: SomeGeneric[int]
    list_field: SomeList[int]

model_instance = TestModel(generic_field=1, list_field=[1, 2])
```
This code fails with exception:
```
Traceback (most recent call last):
  File "pydantic_isuue.py", line 31, in <module>
    class TestModel(BaseModel):
  File "/Users/rnesytov/zvooq/drm/.venv/lib/python3.8/site-packages/pydantic/main.py", line 348, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
generic_field
  some generic error (type=value_error)
```
Looks like `SomeList.validate` were not called.

```
ipdb> {k: v.validators for k, v in TestModel.__fields__.item
s()}                                                        
{'generic_field': [<function SomeGeneric.validate at 0x1064f50d0>], 'list_field': []}
```

And this is true.

After a couple of hours of debugging adventure I think the problem is here https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/fields.py#L457

In my case `self.type_` is `SomeList[int]`, which is concrete type of List generic. For some reason (idk why) `SomeList[int]` doesn't have all attributes of `SomeList` class, including `__get_validators__` method.
And this check will always fail. https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/fields.py#L458 

But there is origin of `SomeList[int]`, which is `SomeList`, which has `__get_validators__`.

```diff
        if issubclass(origin, List):
            # Create self validators
-           get_validators = getattr(self.type_, '__get_validators__', None)
+           get_validators = getattr(origin '__get_validators__', None)
            if get_validators:
                self.class_validators.update(
                    {f'list_{i}': Validator(validator, pre=True) for i, validator in enumerate(get_validators())}
                )

            self.type_ = self.type_.__args__[0]
            self.shape = SHAPE_LIST
```

**Comment by PrettyWood** [comment]
Hello @profx5 

I think it would be `getattr(self.type_, '__get_validators__', None) or getattr(origin '__get_validators__', None)`
for set and list.
For the `Generic` part, we already do `self.type_ = origin`, which solves the problem.
There are currently quite some work on generics as the behaviour depends on python version (this should be tested in python 3.9). Maybe best to work on it once some utils have been written to handle properly the `origin` among other things

**Comment by espdev** [comment]
I suggest to rename the issue to "__get_validators__ method is not called for generic custom types"

A simple example (py3.9):

```python

KType = TypeVar('KType')
VType = TypeVar('VType')

class MyDict(dict[KType, VType]):
    @classmethod
    def __get_validators__(cls):
        print("call __get_validators__")
        yield cls.validate

    @classmethod
    def validate(cls, v):
        raise ValueError("Raise on validation")

class Model(BaseModel):
    foo: MyDict[str, int]
```

`__get_validators__` will never be called in above example.

Also in the following example `__get_validators__` will be called but all default type validators will not be called.

```python
class MyDictStrInt(MyDict[str, int]):
    type_ = dict

class Model(BaseModel):
    foo: MyDictStrInt
```

It seems this is a major issue prevent to use generic custom types.
@PrettyWood what do you think about this?

**Comment by PrettyWood** [comment]
Hi @espdev 
The usual approach is to use `Generic[KT, VT]`.

**Comment by espdev** [comment]
@PrettyWood could you show an example? I do not quite understand your answer.

The following code still does not work
```python
KType = TypeVar('KType')
VType = TypeVar('VType')

class MyDict(dict, Generic[KType, VType]):
    @classmethod
    def __get_validators__(cls):
        print("call __get_validators__")
        yield cls.validate

    @classmethod
    def validate(cls, v):
        raise ValueError("Raise on validation")

class Model(BaseModel):
    foo: MyDict[str, int]

m = Model(foo={'foo': 123})
```

**Comment by PrettyWood** [comment]
Ah sorry you actually want a generic custom type that inherits from `dict` sorry
Yes I think currently the code doesn't handle this case.
We could probably just check `__get_validators__` before all the other origin checks in `_type_analysis` like this
```diff
diff --git a/pydantic/fields.py b/pydantic/fields.py
index 7d0c2a3..75d441d 100644
--- a/pydantic/fields.py
+++ b/pydantic/fields.py
@@ -529,6 +529,14 @@ class ModelField(Representation):
                 self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
             return

+        if hasattr(origin, '__get_validators__') or self.model_config.arbitrary_types_allowed:
+            # Is a Pydantic-compatible generic that handles itself
+            # or we have arbitrary_types_allowed = True
+            self.shape = SHAPE_GENERIC
+            self.sub_fields = [self._create_sub_type(t, f'{self.name}_{i}') for i, t in enumerate(get_args(self.type_))]
+            self.type_ = origin
+            return
+
         if issubclass(origin, Tuple):  # type: ignore
             # origin == Tuple without item type
             args = get_args(self.type_)
@@ -596,13 +604,6 @@ class ModelField(Representation):
             self.sub_fields = [self._create_sub_type(self.type_, f'{self.name}_type')]
         elif issubclass(origin, Type):  # type: ignore
             return
-        elif hasattr(origin, '__get_validators__') or self.model_config.arbitrary_types_allowed:
-            # Is a Pydantic-compatible generic that handles itself
-            # or we have arbitrary_types_allowed = True
-            self.shape = SHAPE_GENERIC
-            self.sub_fields = [self._create_sub_type(t, f'{self.name}_{i}') for i, t in enumerate(get_args(self.type_))]
-            self.type_ = origin
-            return
         else:
             raise TypeError(f'Fields of type "{origin}" are not supported.')
```

@samuelcolvin WDYT? I could have a look at perf impact

**Comment by samuelcolvin** [comment]
Makes sense to me to check `hasattr(origin, '__get_validators__')` first not last.

Probably the `if self.model_config.arbitrary_types_allowed` logic should stay last, but I'm not quite sure.
