### ISSUE TITLE
`_validate_mapping` is not catching ValueError as it should

### ISSUE THREAD

**Issue by pawelswiecki** [samuelcolvin/pydantic#199]
Python 3.6.5, pydantic==0.9.1

```python
from typing import List, Dict, Any

from pydantic import BaseModel


class User(BaseModel):
    data: List[Dict[str, Any]]


data = {
    'data': ['foo']
}
user = User(**data)
```
now:

```bash
13:58 $ python f.py 
Traceback (most recent call last):
  File "f.py", line 13, in <module>
    user = User(**data)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/main.py", line 153, in __init__
    self.__setstate__(self._process_values(data))
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/main.py", line 279, in _process_values
    v_, errors_ = field.validate(value, values, cls=self.__class__)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 227, in validate
    v, errors = self._validate_sequence(v, values, cls)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 242, in _validate_sequence
    single_result, single_errors = self._validate_singleton(v_, values, i, cls)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 281, in _validate_singleton
    value, error = field.validate(v, values, index, cls)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 224, in validate
    v, errors = self._validate_mapping(v, values, cls)
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 257, in _validate_mapping
    v_iter = dict(v)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
What is happening:

```python
v_iter = dict('foo')  # pydantic/fields.py:257
# ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by samuelcolvin** [comment]
can you try with v0.1 which is now released and let us know if it's fixed.

**Comment by pawelswiecki** [comment]
On pydantic==0.10 there is no error! :+1:
