### ISSUE TITLE
Pydantic `dataclasses` break `__eq__` method generated by stdlib `dataclasses` when upgrading from v1.6.1 to v1.7.2

### ISSUE THREAD

**Issue by jtrh** [samuelcolvin/pydantic#2162]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/jtrh/.virtualenvs/tmp-efd3764f8d079be/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29
     optional deps. installed: []
```

```py
import dataclasses
import unittest

import pydantic
import pydantic.dataclasses


class PydanticConfig:
    arbitrary_types_allowed = True


@dataclasses.dataclass(frozen=True)
class StdLibFoo:
    a: str
    b: int


@pydantic.dataclasses.dataclass(frozen=True)
class PydanticFoo:
    a: str
    b: int


@dataclasses.dataclass(frozen=True)
class StdLibBar:
    c: StdLibFoo


@pydantic.dataclasses.dataclass(frozen=True, config=PydanticConfig)
class PydanticBar:
    c: PydanticFoo


@dataclasses.dataclass(frozen=True)
class StdLibBaz:
    c: PydanticFoo


@pydantic.dataclasses.dataclass(frozen=True, config=PydanticConfig)
class PydanticBaz:
    c: StdLibFoo


class DataClassTest(unittest.TestCase):
    def _assert(self, foo, bar):
        self.assertEqual(dataclasses.asdict(foo), dataclasses.asdict(bar.c))
        self.assertEqual(dataclasses.astuple(foo), dataclasses.astuple(bar.c))
        self.assertEqual(foo, bar.c)

    def test_stdlib_only(self):
        foo = StdLibFoo(a='Foo', b=1)
        bar = StdLibBar(c=foo)

        self._assert(foo, bar)

    def test_pydantic_only(self):
        foo = PydanticFoo(a='Foo', b=1)
        bar = PydanticBar(c=foo)

        self._assert(foo, bar)

    def test_pydantic_and_stdlib(self):
        foo = PydanticFoo(a='Foo', b=1)
        bar = StdLibBaz(c=foo)

        self._assert(foo, bar)


    def test_stdlib_and_pydantic(self):
        foo = StdLibFoo(a='Foo', b=1)
        bar = PydanticBaz(c=foo)

        self._assert(foo, bar)


if __name__ == '__main__':
    print(pydantic.version.version_info()); print(); unittest.main(verbosity=2)
```

**Output with `pydantic==1.7.2`**:

```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/jtrh/.virtualenvs/tmp-efd3764f8d079be/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29
     optional deps. installed: []

test_pydantic_and_stdlib (__main__.DataClassTest) ... ok
test_pydantic_only (__main__.DataClassTest) ... ok
test_stdlib_and_pydantic (__main__.DataClassTest) ... FAIL
test_stdlib_only (__main__.DataClassTest) ... ok

======================================================================
FAIL: test_stdlib_and_pydantic (__main__.DataClassTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydantic_dataclass_equality_error_tests_2020_11_30.py", line 73, in test_stdlib_and_pydantic
    self._assert(foo, bar)
  File "pydantic_dataclass_equality_error_tests_2020_11_30.py", line 48, in _assert
    self.assertEqual(foo, bar.c)
AssertionError: StdLibFoo(a='Foo', b=1) != StdLibFoo(a='Foo', b=1)

----------------------------------------------------------------------
Ran 4 tests in 0.001s

FAILED (failures=1)
```

**Output with `pydantic==1.6.1`**:

```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/jtrh/.virtualenvs/tmp-75057fed9773783/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-54-generic-x86_64-with-glibc2.29
     optional deps. installed: []

test_pydantic_and_stdlib (__main__.DataClassTest) ... ok
test_pydantic_only (__main__.DataClassTest) ... ok
test_stdlib_and_pydantic (__main__.DataClassTest) ... ok
test_stdlib_only (__main__.DataClassTest) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```

I think this issue may be related to the automatic conversion of standard library `dataclasses` to Pydantic `dataclasses`. The `__eq__` method generated by the standard library checks that both instances are of the same class (see [`dataclasses._cmp_fn`](https://github.com/python/cpython/blob/v3.8.5/Lib/dataclasses.py#L581) and [`dataclasses._process_class`](https://github.com/python/cpython/blob/v3.8.5/Lib/dataclasses.py#L944-L953)), which is true in 1.6.1 (`assert foo.__class__ is bar.c.__class__` succeeds), but not in 1.7.2 (`assert foo.__class__ is bar.c.__class__` fails, but `assert issubclass(bar.c.__class__, foo.__class__)` succeeds).

**Comment by PrettyWood** [comment]
Hi @jtrh and thanks for reporting!
I guess we could do something like https://github.com/PrettyWood/pydantic/commit/543c0e4777f9d9f9b60767aee07b68704972cafb to keep the original `__eq__`. Maybe add a fallback on the default `__eq__`.

**Comment by samuelcolvin** [comment]
see my comments on this matter on #2182
