### ISSUE TITLE
Comparison 2 fields of model between himself

### ISSUE THREAD

**Issue by david-shiko** [samuelcolvin/pydantic#2272]
### Checks

* [ ]1 I added a descriptive title to this issue
* [ 1] I have searched (google, github) for similar issues and couldn't find anything
* [1 ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [ ] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person

# Question

I have 2 models: 
```
class UserProfileData(BaseModel):
    smoking: Optional[int] = Field(..., ge=0, le=4, description="How mach user = smoking", example=2)
    alcohol: Optional[int] = Field(..., ge=0, le=4, description="How mach user = alcohol", example=2)
    height: Optional[int] = Field(..., ge=50, le=250, description="Height of the user", example=180)
    weight: Optional[int] = Field(..., ge=20, le=200, description="weight of the user", example=80)


class UserSearchPreferences(BaseModel):  # UserProfileData is low boundary
    smoking_high_boudary: Optional[int] = Field(..., ge=0, le=4, description="How mach user = smoking", example=2)
    alcohol_high_boudary: Optional[int] = Field(..., ge=0, le=4, description="How mach user = alcohol", example=2)
    height_high_boudary: Optional[int] = Field(..., ge=50, le=250, description="Height of the user", example=180)
    weight_high_boudary: Optional[int] = Field(..., ge=20, le=200, description="weight of the user", example=80)
```

I want to check that every filed of `something_high_boudary > something`, i.e. `weight_high_boudary > weight`.
Ho I can do it?

**Comment by PrettyWood** [comment]
Hi @david-shiko
You'll need to bind your two models one way or another and then use `validator` on the second field or `root_validator`.
For example
```python
from typing import Dict, Optional

from pydantic import BaseModel, validator


class UserProfileData(BaseModel):
    smoking: Optional[int]
    alcohol: Optional[int]


class UserSearchPreferences(BaseModel):
    smoking_high_boundary: Optional[int]
    alcohol_high_boundary: Optional[int]


class Checker(BaseModel):
    data: UserProfileData
    prefs: UserSearchPreferences

    @validator('prefs')
    def ensure_bigger(cls, u_prefs: UserSearchPreferences, values: dict) -> UserSearchPreferences:
        u_data: UserProfileData = values['data']
        for field, value in u_data:
            high_boundary = getattr(u_prefs, f'{field}_high_boundary', None)
            if value is not None and high_boundary is not None and high_boundary < value:
                raise ValueError(
                    f'Value for {field!r} is too high! '
                    f'(value: {value}, high boundary: {high_boundary})'
                )
        return u_prefs


Checker(
    data=UserProfileData(smoking=1, alcohol=2),
    prefs=UserSearchPreferences(smoking_high_boundary=3, alcohol_high_boundary=5)
)
# OK
try:
    Checker(
        data=UserProfileData(smoking=4, alcohol=2),
        prefs=UserSearchPreferences(smoking_high_boundary=3, alcohol_high_boundary=5)
    )
except ValueError as e:
    print(e)
    # 1 validation error for Checker
    # prefs
    #   Value for 'smoking' is too high! (value: 4, high boundary: 3) (type=value_error)
```
Hope it helps!

**Comment by david-shiko** [comment]
hi @PrettyWood!

Thank you a lot for a help!

I'm verry sorry, but I asked an incrorrect question, because indeed `UserSearchPreferences` inherits from `UserProfileData` (just because it has the same fileds). It's probably must make change a solution.

**Comment by PrettyWood** [comment]
Hi @david-shiko

The easiest would probably be

```python
from typing import Any, Dict, Optional

from pydantic import BaseModel, root_validator


class UserProfileData(BaseModel):
    smoking: Optional[int]
    alcohol: Optional[int]


class UserSearchPreferences(UserProfileData):
    smoking_high_boundary: Optional[int]
    alcohol_high_boundary: Optional[int]

    @root_validator
    def ensure_bigger(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        for field in UserProfileData.__fields__:
            value = values.get(field)
            high_boundary = values.get(f'{field}_high_boundary')
            if value is not None and high_boundary is not None and high_boundary < value:
                raise ValueError(
                    f'Value for {field!r} is too high! '
                    f'(value: {value}, high boundary: {high_boundary})'
                )
        return values


UserSearchPreferences(smoking=1, alcohol=2, smoking_high_boundary=3, alcohol_high_boundary=5)
# OK
try:
    UserSearchPreferences(smoking=4, alcohol=2, smoking_high_boundary=3, alcohol_high_boundary=5)
except ValueError as e:
    print(e)
    # 1 validation error for Checker
    # prefs
    #   Value for 'smoking' is too high! (value: 4, high boundary: 3) (type=value_error)
```

**Comment by david-shiko** [comment]
@PrettyWood!

It's funny, but I can't find out how to extract current incoming values from a such structure ?

```
class UserSearchPreferences(BaseModel):
    smoking: Optional[dict] = {
        'low_boundary': Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2),
        'high_boundary': Field(..., ge=0, le=4, description="Maximum boundary smoking", example=2)}
    alcohol: Optional[dict] = {
        'low_boundary': Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2),
        'high_boundary': Field(..., ge=0, le=4, description="Maximum boundary smoking", example=2)}
```
P.S. I decaded to choose an another way to make it more convient.

**Comment by david-shiko** [comment]
@PrettyWood 

Thank u for a help, by your suggestion I maked another solution (because eventually I fugure out that `UserSearchPreferences` can't inherit form `UserProfile` cuz other reasosns).

My solution:

```
class UserSwipes(BaseModel):  # Consider UserProfile attributes as low boundary
    smoking_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    smoking_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)
    alcohol_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    alcohol_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)
    kids_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    kids_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)
    height_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    height_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)
    weight_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    weight_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)
    sport_low: Optional[int] = Field(..., ge=0, le=4, description="Minimal boundary smoking", example=2)
    sport_high: Optional[int] = Field(..., ge=0, le=4, description="Maximum boundary smoking", example=3)

    @root_validator
    def ensure_bigger(cls, values: dict[str]) -> dict[str]:
        old_k_v = next(iter(values.items()))  # Get tuple first pair of key-value
        for k, v in values.items():
            if 'low' in k:
                old_k_v = k, v
            else:
                if k.split('_')[0] == old_k_v[0].split('_')[0]:
                    if old_k_v[-1] > v:
                        raise Exception('Minimal value biggest that Maximum item!')
                else:
                    raise Exception("'high' item must follow 'low' item.")
        return values
```

I tryied to link `low` and `high` somehow (dict or list, but failed, as I understood, pydantic can't combine `Field`-s.

P.S. I also come accross with another [question](https://stackoverflow.com/q/65836195/14190526) (stackoverflow)

**Comment by PrettyWood** [comment]
Here is a little helper
```python
from typing import Optional, Type, TypeVar

from pydantic import BaseModel, create_model

BaseModelT = TypeVar('BaseModelT', bound=BaseModel)

def to_optional(model: Type[BaseModelT], name: Optional[str] = None) -> Type[BaseModelT]:
    """
    Create a new BaseModel with the exact same fields as `model`
    but making them all optional
    """
    field_definitions = {
        name: (field.outer_type_, None)
        for name, field in model.__fields__.items()
    }
    return create_model(name or f'Optional{model.__name__}', **field_definitions)  # type: ignore[arg-type]


class Model(BaseModel):
    a: str
    b: int


print(Model.__fields__)
# {'a': ModelField(name='a', type=str, required=True), 'b': ModelField(name='b', type=int, required=True)}
print(to_optional(Model).__fields__)
# {'a': ModelField(name='a', type=Optional[str], required=False, default=None), 'b': ModelField(name='b', type=Optional[int], required=False, default=None)}

class Test(to_optional(Model)):
    x: bool

print(Test.__fields__)
# {'a': ModelField(name='a', type=Optional[str], required=False, default=None), 'b': ModelField(name='b', type=Optional[int], required=False, default=None), 'x': ModelField(name='x', type=bool, required=True)}
```

Hope it helps ;)

**Comment by david-shiko** [comment]
Fine! I added an answer to the portal. Can I share a cup of coffee with you?

**Comment by david-shiko** [comment]
@PrettyWood Unfortunately this solution isn't working correctly with `FastAPI`. it's missing field info (example, description, i.e. like
```
Field(
        ..., max_length=16,
        description="One of the media types",
        example='photo')   
```

**Comment by PrettyWood** [comment]
Ah yes sorry my bad my solution didn't support complex fields (with `Field(........)` syntax)
How about that?

```python
from copy import deepcopy
from pprint import pprint
from typing import Optional, Type, TypeVar

from pydantic import BaseModel, Field, create_model

BaseModelT = TypeVar('BaseModelT', bound=BaseModel)


def to_optional(model: Type[BaseModelT], name: Optional[str] = None) -> Type[BaseModelT]:
    """
    Create a new BaseModel with the exact same fields as `model`
    but making them all optional
    """
    field_definitions = {}
    for name, field in model.__fields__.items():
        optional_field_info = deepcopy(field.field_info)
        # Do not change default value of fields that are already optional
        if optional_field_info.default is ...:
            optional_field_info.default = None
        field_definitions[name] = (field.outer_type_, optional_field_info)

    return create_model(name or f'Optional{model.__name__}', **field_definitions)  # type: ignore[arg-type]


class Model(BaseModel):
    a: str
    b: str = 'default_b'
    c: str = Field(..., alias='alias_c')
    d: str = Field('default_d', alias='alias_d')


pprint(Model.__fields__)
# {
#   'a': ModelField(name='a', type=str, required=True),
#   'b': ModelField(name='b', type=str, required=False, default='default_b'),
#   'c': ModelField(name='c', type=str, required=True, alias='alias_c'),
#   'd': ModelField(name='d', type=str, required=False, default='default_d', alias='alias_d')
# }
pprint(to_optional(Model).__fields__)
# {
#   'a': ModelField(name='a', type=Optional[str], required=False, default=None),
#   'b': ModelField(name='b', type=str, required=False, default='default_b'),
#   'c': ModelField(name='c', type=Optional[str], required=False, default=None, alias='alias_c'),
#   'd': ModelField(name='d', type=str, required=False, default='default_d', alias='alias_d')
# }
```

**Comment by david-shiko** [comment]
> Ah yes sorry my bad my solution didn't support complex fields (with `Field(........)` syntax)
> How about that?
> 
> ```python
> from copy import deepcopy
> from pprint import pprint
> from typing import Optional, Type, TypeVar
> 
> from pydantic import BaseModel, Field, create_model
> 
> BaseModelT = TypeVar('BaseModelT', bound=BaseModel)
> 
> 
> def to_optional(model: Type[BaseModelT], name: Optional[str] = None) -> Type[BaseModelT]:
>     """
>     Create a new BaseModel with the exact same fields as `model`
>     but making them all optional
>     """
>     field_definitions = {}
>     for name, field in model.__fields__.items():
>         optional_field_info = deepcopy(field.field_info)
>         # Do not change default value of fields that are already optional
>         if optional_field_info.default is ...:
>             optional_field_info.default = None
>         field_definitions[name] = (field.outer_type_, optional_field_info)
> 
>     return create_model(name or f'Optional{model.__name__}', **field_definitions)  # type: ignore[arg-type]
> 
> 
> class Model(BaseModel):
>     a: str
>     b: str = 'default_b'
>     c: str = Field(..., alias='alias_c')
>     d: str = Field('default_d', alias='alias_d')
> 
> 
> pprint(Model.__fields__)
> # {
> #   'a': ModelField(name='a', type=str, required=True),
> #   'b': ModelField(name='b', type=str, required=False, default='default_b'),
> #   'c': ModelField(name='c', type=str, required=True, alias='alias_c'),
> #   'd': ModelField(name='d', type=str, required=False, default='default_d', alias='alias_d')
> # }
> pprint(to_optional(Model).__fields__)
> # {
> #   'a': ModelField(name='a', type=Optional[str], required=False, default=None),
> #   'b': ModelField(name='b', type=str, required=False, default='default_b'),
> #   'c': ModelField(name='c', type=Optional[str], required=False, default=None, alias='alias_c'),
> #   'd': ModelField(name='d', type=str, required=False, default='default_d', alias='alias_d')
> # }
> ```
@PrettyWood Unfortunately this solution isn't working because of another subtle error: 
`ValueError: On field "category" the following field constraints are set but not enforced: max_length.`

**Comment by PrettyWood** [comment]
Ah yes this is tricky as the type is already resolved. You could handle this special case by checking in the `__mro__` but probably easier to first try this solution, which just checks for the initial type in the `__annotations__`

```python
from copy import deepcopy
from typing import Optional, Type, TypeVar

from pydantic import BaseModel, create_model

BaseModelT = TypeVar('BaseModelT', bound=BaseModel)


def to_optional(model: Type[BaseModelT], name: Optional[str] = None) -> Type[BaseModelT]:
    """
    Create a new BaseModel with the exact same fields as `model`
    but making them all optional
    """
    field_definitions = {}

    for name, field in model.__fields__.items():
        optional_field_info = deepcopy(field.field_info)
        # Do not change default value of fields that are already optional
        if optional_field_info.default is ...:
            optional_field_info.default = None

        field_type = model.__annotations__.get(name) or field.outer_type_
        field_definitions[name] = (field_type, optional_field_info)

    return create_model(name or f'Optional{model.__name__}', **field_definitions)  # type: ignore[arg-type]
```

**Comment by david-shiko** [comment]
For some reason, I can't inherit from schemas with `to_optional`.

```
class UserLogIn(BaseModel):
    email: EmailStr = Field(default=..., description="email", example='0@gmail.com')
    password: str = Field(default=..., min_length=8, max_length=64, description="pass", example='blah blah')

    @validator('password')
    def password_hashing(cls, v):
        return pwd_context.hash(v)

class UserCreate(UserLogIn):  # FEATURE add location
    avatar: HttpUrl = Field(default=..., description="Avatar", example="https://picsum.photos/200")
    first_name: str = Field(default=..., max_length=20, description="First name, a single word", example='Ivan')
    gender: int = Field(default=..., ge=1, le=2, description="1 is male, 2 is female", example=1)
    birthdate: date = Field(default=..., description="Age, two digits", example='1980-1-1')
    comment: Optional[str] = Field(default=None, max_length=512, description="lorem ipsum ", example='blah blah')

    @validator('birthdate')
    def date_validation(cls, v):
        if not date(year=1950, month=1, day=1) < v < date(year=2011, month=1, day=1):
            raise ValueError(f'birthdate must be in range '
                             f'{date(year=1950, month=1, day=1)} - {date(year=2011, month=1, day=1)}')

    class Config:
        orm_mode = True
        
class UserUpdate(to_optional(UserCreate)):

    class Config:
        orm_mode = True
        
        
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/david/PycharmProjects/rubik_love_api/app/schemas.py", line 205, in <module>
    class UserUpdate(to_optional(UserCreate), UserIcons):
  File "/home/david/PycharmProjects/rubik_love_api/app/schemas.py", line 113, in to_optional
    return create_model(name or f'Optional{model.__name__}', **field_definitions)
  File "pydantic/main.py", line 930, in pydantic.main.create_model
  File "pydantic/main.py", line 262, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 314, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 951, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "password" the following field constraints are set but not enforced: min_length, max_length. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by PrettyWood** [comment]
Here is a patched version
```py
def to_optional(model: Type[BaseModelT], name: Optional[str] = None) -> Type[BaseModelT]:
    """
    Create a new BaseModel with the exact same fields as `model`
    but making them all optional
    """
    all_annotations = {}
    # Workaround to retrieve the passed type and not the resolved one
    # (e.g. `str` with constraints that resolved in `ConstrainedStrValue`)
    for base in reversed(model.__bases__):
        all_annotations.update(getattr(base, '__annotations__', {}))
    all_annotations.update(model.__annotations__)

    field_definitions = {}

    for name, field in model.__fields__.items():
        optional_field_info = deepcopy(field.field_info)
        # Do not change default value of fields that are already optional
        if optional_field_info.default is ...:
            optional_field_info.default = None

        field_type = all_annotations.get(name, field.outer_type_)
        field_definitions[name] = (field_type, optional_field_info)

    return create_model(name or f'Optional{model.__name__}', **field_definitions)  # type: ignore[arg-type]
```

**Comment by david-shiko** [comment]
Howdy there after a long quiet! :)
I applied a code from [this](https://github.com/samuelcolvin/pydantic/issues/2272#issuecomment-771205557) comment. It's working well, but how I can validate the field if it exists?

Example:
```
class PhoneNumber(BaseModel):
    phone_number: str = Field(default=..., min_length=8, max_length=20, description="Номер телефона", example='+79319643333')  # TODO make me with spaces
    class Config:
        orm_mode = True

    @validator('phone_number')
    def valid_phone(cls, v: str):
        phone_number_obj = phonenumbers.parse(number=v)  # Raise error if not seems like a phone number
        phone_number = f"+7{''.join([i for i in v if i.isdecimal()])[1:]}"
        if not phonenumbers.is_valid_number(phone_number_obj) or len(phone_number) < 10:  # TODO test it
            raise ValueError('Incorrect phone number')
        return phone_number


class UserLogIn(PhoneNumber):
    full_name: str = Field(default=..., description="ФИО", example='Чехов Антон Павлович')
    class Config:
        orm_mode = True
        
class UserUpdate(to_optional(model=UserLogIn, name='UserUpdate')):
    class Config:
        orm_mode = True
        
new_user = UserUpdate(**{'phone_number': '+7 931 964 foo'})  # No throw error :(
```

**Comment by PrettyWood** [comment]
@david-shiko I updated the code above :) Just forgot the `__base__` to inherit all the fields. I also fixed the `name` of the class which was overwritten by the for loop. Hope it helps!

**Comment by david-shiko** [comment]
Suddenly I got an error for this schemes:

Parent scema:
```
class ClinicCreate(FullName):
    clinic_full_name: str = Field(
        default=...,
        max_length=128,
        description="Полное название организации/мед. учреждения.",
        example='Общая бесплатная непрофильная городская больница №52 Имени Амосова Николай Михайловича')

    clinic_short_name: str = Field(
        default=...,
        max_length=64,
        description="Сокращенное название организации/мед. учреждения.",
        example='Городская больница №52.')

    clinic_phone_number: PhoneNumber

    manager_phone_number: PhoneNumber

    manager_login: str = Field(
        default=...,
        min_length=4,
        max_length=32,
        description="Логин руководителя",
        example='Cool Manager')

    password: Password

    @root_validator()
    def rename_fields_for_db(cls, values):
        values['manager_full_name'] = values['full_name']
        values['full_name'] = values['clinic_full_name']
        values['short_name'] = values['clinic_short_name']
        del values['clinic_full_name']
        del values['clinic_short_name']
        # No mess and delete "full_name". Incoming full_name is manager_full_name, output full_name is clinic_full_name
        return values
```

Child schema:
```
class ClinicUpdate(to_optional(model=ClinicCreate, model_name='ClinicUpdate')):
    pass
 ```

Error:
```
    for field_name, field in model.__fields__.items():
AttributeError: type object 'ClinicCreate' has no attribute '__fields__'
```

**Comment by PrettyWood** [comment]
what is your `FullName`?

**Comment by david-shiko** [comment]
```
class FullName(str):
    min_length = 4
    max_length = 64

    @classmethod
    def validate_full_name(cls, v: str):
        for letter in v:
            if not letter.isascii():
                raise ValueError('Only ascii symbols allowed (mainly english letter, common symbols and digests)!')
        if len(v.split()) < 2:
            raise ValueError('Incorrect full name')
        return v

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(description="ФИО (логин) пользователя",
                            example='Чехов Антон Павлович')

    @classmethod
    def __get_validators__(cls):
        yield cls.validate_full_name
        yield validators.constr_length_validator
```

**Comment by PrettyWood** [comment]
`ClinicCreate` is not a `BaseModel` then so it has no `__fields__` indeed

**Comment by david-shiko** [comment]
Ohh, Thank you! I forgot to change parent after refactoring, sorry for the inconvenience.

**Comment by lovetoburnswhen** [comment]
> Here is a patched version
> 
> ```python
> from copy import deepcopy
> from typing import Optional, Type, TypeVar
> 
> from pydantic import BaseModel, create_model
> 
> BaseModelT = TypeVar('BaseModelT', bound=BaseModel)
> 
> 
> def to_optional(model: Type[BaseModelT], model_name: Optional[str] = None) -> Type[BaseModelT]:
>     """
>     Create a new BaseModel with the exact same fields as `model`
>     but making them all optional
>     """
>     all_annotations = {}
>     # Workaround to retrieve the passed type and not the resolved one
>     # (e.g. `str` with constraints that resolved in `ConstrainedStrValue`)
>     for base in reversed(model.__bases__):
>         all_annotations.update(getattr(base, '__annotations__', {}))
>     all_annotations.update(model.__annotations__)
> 
>     field_definitions = {}
> 
>     for field_name, field in model.__fields__.items():
>         optional_field_info = deepcopy(field.field_info)
>         # Do not change default value of fields that are already optional
>         if optional_field_info.default is ...:
>             optional_field_info.default = None
> 
>         field_type = all_annotations.get(field_name, field.outer_type_)
>         field_definitions[field_name] = (field_type, optional_field_info)
> 
>     return create_model(
>         model_name or f'Optional{model.__name__}',
>         __base__=model,
>         **field_definitions  # type: ignore[arg-type]
>     )
> ```

Shouldn't `field_type` be wrapped in `typing.Optional`?
