### ISSUE TITLE
typing.Pattern json_encoder Config not working

### ISSUE THREAD

**Issue by XuhuiSun95** [samuelcolvin/pydantic#2301]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
OS: python:3.9-alpine docker image

Reproduce the same result from python:3.8-apline and python:3.7-alpine image

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: False
                 install path: /usr/local/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Dec 17 2020, 01:59:58)  [GCC 9.3.0]
                     platform: Linux-5.4.0-65-generic-x86_64-with
     optional deps. installed: ['typing-extensions']

```

```py
from typing import Pattern

from pydantic import BaseModel


def pattern_encoder(x: Pattern) -> str:
    return x.pattern


class A(BaseModel):
    p: Pattern

    class Config:
        json_encoders = {
            Pattern: pattern_encoder,
        }


class B(BaseModel):
    p: Pattern

    class Config:
        json_encoders = {
            Pattern: lambda x: x.pattern,
        }


a = A(p="^")
b = B(p="^")


# not work
# print(a.json())

# this works but I thought the one above should be working unless I am missing something
print(a.json(encoder=pattern_encoder))

# not work
# print(b.json())

# the same as above
print(b.json(encoder=pattern_encoder))
...
```
Exception if I use `a.json()`, or `b.json()`:
```bash
Traceback (most recent call last):
  File "/opt/app/test.py", line 33, in <module>
    print(a.json())
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 506, in json
    return self.__config__.json_dumps(data, default=encoder, **dumps_kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/pydantic/json.py", line 77, in custom_pydantic_encoder
    return pydantic_encoder(obj)
  File "/usr/local/lib/python3.9/site-packages/pydantic/json.py", line 65, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'Pattern' is not JSON serializable
```

**Comment by PrettyWood** [comment]
Hi @XuhuiSun95 
A fix has already been done in #2056 and merged in 4020ebc41232adfe132cc8628be59ccb18d8f202
This will be available in 1.8.
In the meantime you can install pydantic with the right merge commit
`pip install -U git+https://github.com/samuelcolvin/pydantic.git@4020ebc41232adfe132cc8628be59ccb18d8f202`
Hope it helps!

**Comment by XuhuiSun95** [comment]
@PrettyWood Thanks!  Discover this a little earlier from master and 1.7.3 difference.

Do you know when 1.8 will be released? In the meantime, I might just stick with 1.7.3 and use the `encoder=pattern_encoder` way since everything else in my code base is working properly.

**Comment by PrettyWood** [comment]
I don't know tbh. Hopefully in one or two months
