### ISSUE TITLE
'<empty space>' is valid for Field(min_length=1, strip_whitespace=True) 

### ISSUE THREAD

**Issue by 1oglop1** [samuelcolvin/pydantic#2315]
# Bug

I'm trying to use common requirement for a non-empty string with a minimum length.

I know I can write a custom validator but it feels unnecessary for this simple case.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /.../lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Feb  1 2021, 09:34:25)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

```py
from pydantic import BaseModel, Field


class NonEmptyString(BaseModel):
    s1: str = Field(min_length=1, strip_whitespace=True)
    s2: str = Field(strip_whitespace=True, min_length=1)


nes = NonEmptyString(s1=" ", s2=' ')

print(nes)
print(f"'{nes.s1}'")
print(f"'{nes.s2}'")
```

**Actual result:**

```
s1=' ' s2=' '
' '
' '
```

**Expected**

Exception similar to this

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NonEmptyString
s2
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
  ```

**Comment by PrettyWood** [comment]
Hi @1oglop1 
You should use `constr`
```py
s1: constr(strip_whitespace=True, min_length=1)
```

**Comment by 1oglop1** [comment]
@PrettyWood it's not possible for me to use `constr` like a type because it fails with `mypy` even when using `pydantic` plugin. Solution using `Field` was suggested in another issue and was working correctly for everything except this case.

your solution resolves into mypy error

```
schemas.py:40: error: Invalid type comment or annotation
schemas.py:40: note: Suggestion: use constr[...] instead of constr(...)
```

another workaround is to use `# type: ignore` for mypy but I still do not see it as desired behaviour

```
class NonEmptyString(BaseModel):
    s1: str = Field(min_length=1, strip_whitespace=True)
    s2: str = Field(strip_whitespace=True, min_length=1)
    s3: constr(strip_whitespace=True, min_length=1)  # type: ignore
```

**Comment by PrettyWood** [comment]
Ok I understand. Using directly the `con*()` functions doesn't work well with `mypy` :/

For now the best is probably to do
```py
from pydantic import BaseModel, ConstrainedStr


class StrippedNotEmptyStr(ConstrainedStr):
    min_length = 1
    strip_whitespace = True


class Model(BaseModel):
    s1: str
    s2: StrippedNotEmptyStr
```
Hope it helps!

Closing this issue since it's related to https://github.com/samuelcolvin/pydantic/issues/975.

**Comment by 1oglop1** [comment]
@PrettyWood Thanks this looks like a good workaround to me :)
