### ISSUE TITLE
[Help needed] TypeError: __init__() missing 2 required positional arguments: 'attr' and 'value'

### ISSUE THREAD

**Issue by spacemanspiff2007** [samuelcolvin/pydantic#2340]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: C:\my_venv\Lib\site-packages\pydantic
               python version: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10
     optional deps. installed: []
```

I have a FastAPI application which crashes reproducible when trying to serialize to a dict.

This is my model that does get created from an orm object.
```python
from datetime import datetime
from typing import Optional, Dict, Union, Any
from pydantic import BaseModel, UUID4

class MyModel(BaseModel):
    uuid: UUID4
    name: Optional[str]
    description: Optional[str]

    dt: datetime

    cfg_1: Dict[str, Union[int, float, str]]
    cfg_2: Dict[str, Union[int, float, str]]

    info: Dict[str, Any]

    @classmethod
    def from_db(cls, orm_obj):

        return cls(
            uuid=orm_obj.uuid, name=orm_obj.name, description=orm_obj.desc,
            cfg_1=orm_obj.cfg_1, cfg_2=orm_obj.cfg_2,
            info=dict(orm_obj.info), dt=orm_obj.dt
        )
```

This is my FastAPI Code;
```python
def get_instance_all(uuid: UUID4):
    with orm.db_session:
        try:
            obj = MyModelOrm[str(uuid)]    # type: MyModelOrm
        except orm.ObjectNotFound as e:
            return orm_to_response(e)

    instance = MyModel.from_db(obj)
    instance.dict()
```

which leads to the following error message
```
  File "C:\FastApiApp\mode_instance.py", line 110, in get_instance_all
    instance.dict()
  File "pydantic\main.py", line 459, in pydantic.main.BaseModel.dict
  File "pydantic\main.py", line 802, in _iter
  File "pydantic\main.py", line 716, in pydantic.main.BaseModel._get_value
  File "pydantic\main.py", line 732, in pydantic.main.BaseModel._get_value
TypeError: __init__() missing 2 required positional arguments: 'attr' and 'value'
```

If I keep the ``info`` field empty (e.g. ``info={}, dt=orm_obj.dt``) everything works as expected and the error message disappears.
If the info gets set to a fix value (e.g. ``info={'errors': [], 'version': 1}, dt=orm_obj.dt``) the error comes back.

I tried to create a snipped to reproduce the problem, however it does not occur there.
Currently I don't know how to proceed.
Since I can create the model instance successfully all data should actually be in the correct format and it's not clear to me why serializing fails.
Any ideas what I can do to further isolate the problem?

**Comment by spacemanspiff2007** [comment]
Good news:
I can reproduce the issue with this snippet (requires package ``pony``). 
However I'm unsure if this is a bug in pony or in pydantic.

```python
import typing
from typing import Dict, Union, List

from pony import orm
from pydantic import BaseModel

db = orm.Database()


class OrmObj(db.Entity):
    id: int = orm.PrimaryKey(int, auto=True)

    # configuration
    test_list: typing.List[str] = orm.Required(orm.Json, default=[])
    test_dict: typing.Dict[str, typing.Any] = orm.Required(orm.Json, default={})

    # information about the test instance
    test_mixed: typing.Dict[str, typing.Any] = orm.Required(orm.Json, default={})


db.bind(provider='sqlite', filename=':memory:', create_db=True)
db.generate_mapping(check_tables=True, create_tables=True)


class PydModel(BaseModel):
    id: int

    test_list: List[str]
    test_dict: Dict[str, Union[int, float, str]]

    test_mixed: Dict[str, typing.Any]


# This works
with orm.db_session:
    obj = OrmObj(test_list=['1'], test_dict={'a': 'b'}, test_mixed={})
m = PydModel(id=obj.id, test_list=obj.test_list, test_dict=obj.test_dict, test_mixed=obj.test_mixed)
m.dict()

with orm.db_session:
    obj = OrmObj(test_list=['1'], test_dict={'a': 'b'}, test_mixed={'a': [], 'c': {}})
m = PydModel(id=obj.id, test_list=obj.test_list, test_dict=obj.test_dict, test_mixed=obj.test_mixed)
m.dict()  # <-- This crashes
```

Output:
```
Traceback (most recent call last):
  File "__test__.py", line 118, in <module>
    m.dict()  # <-- This crashes
  File "pydantic\main.py", line 459, in pydantic.main.BaseModel.dict
  File "pydantic\main.py", line 802, in _iter
  File "pydantic\main.py", line 716, in pydantic.main.BaseModel._get_value
  File "pydantic\main.py", line 732, in pydantic.main.BaseModel._get_value
TypeError: __init__() missing 2 required positional arguments: 'attr' and 'value'
```

**Comment by PrettyWood** [comment]
Hi @spacemanspiff2007 
It's the same issue as this one https://github.com/samuelcolvin/pydantic/issues/1221 ;)

The issue is the following
```py
with orm.db_session:
    obj = OrmObj(test_list=['1'], test_dict={'a': 'b'}, test_mixed={'a': [], 'c': {}})
m = PydModel(id=obj.id, test_list=obj.test_list, test_dict=obj.test_dict, test_mixed=obj.test_mixed)

print({k: type(v) for k, v in obj.test_mixed.items()})
# {'a': <class 'pony.orm.ormtypes.TrackedList'>, 'c': <class 'pony.orm.ormtypes.TrackedDict'>}
```
the list and the dict coming from the ORM are not builtin list and dict anymore and can not be parsed by default by pydantic.

**Comment by spacemanspiff2007** [comment]
> Hi @spacemanspiff2007
> It's the same issue as this one #1221 ;)

Argh - I just searched for the error message - sorry. 😕 

> Hope it helps

Definitely big time!

However I am unsure if the code example you posted does also work with deeper nested list/dicts.
As far as I understand it this will only work for the topmost level when accessing the structure.
Imho I'll have to recursively cast to dict/list in the returned structure from the orm.

**Comment by PrettyWood** [comment]
It should work for recursive structures and `TrackedDict` already works because we use `.items()` method, only `TrackedList` is a problem

**Comment by spacemanspiff2007** [comment]
Thank you very much for you help!
