### ISSUE TITLE
Support min_length on Fields of type typing.Sized

### ISSUE THREAD

**Issue by Ran4** [samuelcolvin/pydantic#2404]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: False
                 install path: /tmp/foo/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

### Code example

```py
from typing import Sized
from pydantic import BaseModel, Field


class SomeModel(BaseModel):
    value: Sized = Field(..., min_length=1)


SomeModel(value=[4])
```

### Expected

This should work, since `typing.Sized` specifies that we have a `__len__` method, and thus we should be able to check the minimum length of the object we're validating.

### Observed

```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    class SomeModel(BaseModel):
  File "/tmp/foo/pydantic/pydantic/main.py", line 302, in __new__
    fields[ann_name] = ModelField.infer(
  File "/tmp/foo/pydantic/fields.py", line 387, in infer
    annotation = get_annotation_from_field_info(annotation, field_info, name, config.validate_assignment)
  File "/tmp/foo/pydantic/schema.py", line 914, in get_annotation_from_field_info
    raise ValueError(
ValueError: On field "value" the following field constraints are set but not enforced: min_length.
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by samuelcolvin** [comment]
this is not a bug, but a feature request, please create a discussion as described in issue type picker.
