### ISSUE TITLE
Cannot have a nested frozen dataclass as field in a BaseModel

### ISSUE THREAD

**Issue by yoavg** [samuelcolvin/pydantic#2541]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/yogo/.local/share/virtualenvs/server-Fv_PcELd/lib/python3.7/site-packages/pydantic
               python version: 3.7.9 (default, Nov 20 2020, 18:45:38)  [Clang 12.0.0 (clang-1200.0.32.27)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Here is a minimal code that reproduces the failure.
(this possibly relates to / is an extension of #2065 )
```py
from dataclasses import dataclass
import pydantic

from pydantic import BaseModel

@dataclass(frozen=True)
class T:
    bla: int

@dataclass(frozen=True)
class Item:
    name: str
    b: T

class Example(BaseModel):
    item: pydantic.dataclasses.dataclass(Item, frozen=True)

print(Example.schema_json())
```

**Comment by PrettyWood** [comment]
Hi @yoavg 
This has nothing to do with _pydantic_ per se. You would have the same error with plain `dataclass`
```py
import dataclasses

@dataclasses.dataclass(frozen=True)
class T:
    bla: int


@dataclasses.dataclass(frozen=True)
class Item:
    name: str
    b: T

NewItem = dataclasses.dataclass(Item, frozen=True)
```

In your case you just need to write
```py
class Example(BaseModel):
    item: Item  # or pydantic.dataclasses.dataclass(Item) but the conversion is done automatically
```
Hope it helps!

**Comment by yoavg** [comment]
Thank you for the response, but I tried the proposed approach before opening the issue, and re-tried again now. It doesn't work, and I get the same error.
To be clear, the error I am seeing is:

```
Traceback (most recent call last):
  File "tmp.py", line 18, in <module>
    print(Example.schema_json())
  File "pydantic/main.py", line 715, in pydantic.main.BaseModel.schema_json
  File "pydantic/main.py", line 704, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 164, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 350, in pydantic.schema.get_flat_models_from_model
  File "pydantic/schema.py", line 400, in pydantic.schema.get_flat_models_from_fields
  File "pydantic/schema.py", line 373, in pydantic.schema.get_flat_models_from_field
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
    f'repr={self.repr!r},'
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
    f'name={self.name!r},'
  File "pydantic/dataclasses.py", line 158, in pydantic.dataclasses._process_class
    # factory will be used.  This is given a nice repr() which will appear
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1010, in dataclass
    return wrap(_cls)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 1002, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 879, in _process_class
    raise TypeError(f'1{cls} {cls.__mro__} cannot inherit non-frozen dataclass from a '
TypeError: 1<class 'pydantic.dataclasses._Pydantic_Item_140625865647440'> (<class 'pydantic.dataclasses._Pydantic_Item_140625865647440'>, <class '__main__.Item'>, <class 'object'>) cannot inherit non-frozen dataclass from a frozen one
```

**Comment by PrettyWood** [comment]
Ok! I'll add tests for this but #2557 fixes this ;)

**Comment by PrettyWood** [comment]
Ok! I will add this test in #2557 ;)

**Comment by PrettyWood** [comment]
Note that my remark will still be valid with the fix. The fix won't handle "double frozen" config

**Comment by yoavg** [comment]
I am happy without needing to do explicit conversion myself, if following works, that'd be great:
```python
class Example(BaseModel):
   item: Item
```

By "nested frozen", I meant the `T` under `Item`, and the issue is that this crashes pydantic when asking for a schema. Doing explicit conversion + marking frozen=True in the conversion was just my attempt to get around the initial version (which is as above) not working.

**Comment by haf** [comment]
Similar:

```
  File "/Users/haf/.pyenv/versions/3.9.10/lib/python3.9/dataclasses.py", line 1012, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Users/haf/.pyenv/versions/3.9.10/lib/python3.9/dataclasses.py", line 892, in _process_class
    raise TypeError(f'cannot inherit non-frozen dataclass ({any_frozen_base}) from a '
TypeError: cannot inherit non-frozen dataclass (<class 'mmm.model.dtos.AppCtr'>) from a frozen one (<class 'pydantic.dataclasses._Pydantic_AppCtr_4471617408'>)
```

When using the docs endpoint in FastAPI. The class looks like:

```python
@dataclass(eq=True, frozen=True)
class AppCtr:
    app_id: UUID
    country: str
    def as_app_ctr_curr(self, currency: str) -> AppCtrCurr:
        return AppCtrCurr(app_id=self.app_id, country=self.country, currency=currency)
```

**Comment by haf** [comment]
https://github.com/tiangolo/fastapi/issues/4763
