### ISSUE TITLE
dataclasses decorator doesn't handle unannotated stdlib dataclass types when nested

### ISSUE THREAD

**Issue by antonl** [samuelcolvin/pydantic#2594]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

It appears that `dataclasses.dataclass` doesn't create the `__annotations__` field when there are no fields. The `pydantic.dataclasses.dataclass` decorator assumes that it exists [here](https://github.com/samuelcolvin/pydantic/blob/5b237b3ea66e46c1a2950b2617dbb9e40a0b0836/pydantic/dataclasses.py#L148). Declaring it a pydantic dataclass fixes the issue.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /opt/miniconda3/envs/te-bug-test/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0]
                     platform: Linux-5.11.0-051100-generic-x86_64-with-glibc2.10
     optional deps. installed: ['typing-extensions']
...
```

Reproducer: 
```py
from dataclasses import dataclass as stdlib_dataclass
from pydantic.dataclasses import dataclass as validated_dataclass

@stdlib_dataclass  # replacing this with @validated_dataclass fixes this
class Trivial:
    pass


@validated_dataclass
class NestedVTrivial:
    child: validated_dataclass(Trivial)
```

Results in a traceback
```python traceback
Traceback (most recent call last):
  File "/app/extra/plugins/python/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/app/extra/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/aloukian/.var/app/com.jetbrains.PyCharm-Professional/config/JetBrains/PyCharm2020.3/scratches/pydantic_annotations_bug.py", line 10, in <module>
    @validated_dataclass
  File "/home/aloukian/.var/app/com.jetbrains.PyCharm-Professional/config/JetBrains/PyCharm2020.3/scratches/pydantic_annotations_bug.py", line 12, in NestedVTrivial
    child: validated_dataclass(Trivial)
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
    f'repr={self.repr!r},'
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
    f'name={self.name!r},'
  File "pydantic/dataclasses.py", line 148, in pydantic.dataclasses._process_class
    # __eq__ method in the class body (not one that was created by
AttributeError: type object 'Trivial' has no attribute '__annotations__'
```

**Comment by PrettyWood** [comment]
Hi @antonl and thanks for reporting! Fixed my PR to support your issue

**Comment by aantn** [comment]
Any progress with this? I'm encountering the same issue.

**Comment by PrettyWood** [comment]
@aantn you're welcome to try out the PR in the meantime
