### ISSUE TITLE
Cannot generate a JSON Schema for a Pydantic model featuring a custom generic class field

### ISSUE THREAD

**Issue by anatoly-scherbakov** [samuelcolvin/pydantic#2598]
### Checks

* [*] I added a descriptive title to this issue
* [*] I have searched (google, github) for similar issues and couldn't find anything
* [*] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: False
                 install path: /home/anatoly/projects/builder/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Dec 28 2020, 18:55:09)  [GCC 9.3.0]
                     platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Intent.** Using Pydantic with OpenAPI, I am trying to validate a comma-separated GET parameter (say, `red,white`) against a custom class `CommaSeparated[Set[Color]]` and get `{Color.RED, Color.WHITE}` as a clean validated value.

The initiative breaks when generating the docs because JSON Schema for this model cannot be properly generated. I have looked for this `AssertionError` but did not find anything so far.

```py
from enum import Enum
from typing import Optional, Generic, TypeVar, Set

from pydantic import BaseModel, version
from pydantic.fields import ModelField
from pydantic.schema import model_schema

ContainerType = TypeVar('ContainerType')


class Color(str, Enum):
    """Cat colors."""

    RED = 'red'
    WHITE = 'white'
    BLACK = 'black'


class CommaSeparated(Generic[ContainerType]):
    """Comma separated values of a container."""

    @classmethod
    def __get_validators__(cls):
        """Ensure pydantic compatibility."""
        yield cls.validate

    @classmethod
    def validate(cls, raw_value: str, field: ModelField) -> ContainerType:
        """Validate the raw value."""
        raise ValueError(
            'I will write this validation later, too lazy right now :(',
        )


class CatsQuery(BaseModel):
    """Query our cats herd."""

    color__in: Optional[CommaSeparated[Set[Color]]] = None


print(f'Pydantic version: {version.VERSION}')
model_schema(CatsQuery)

'''
Output:

    Pydantic version: 1.7.3
    
    tests/test_comma_separated_query_strings.py:None (tests/test_comma_separated_query_strings.py)
    test_comma_separated_query_strings.py:42: in <module>
        model_schema(CatsQuery)
    ../venv/lib/python3.8/site-packages/pydantic/schema.py:153: in model_schema
        m_schema, m_definitions, nested_models = model_process_schema(
    ../venv/lib/python3.8/site-packages/pydantic/schema.py:525: in model_process_schema
        m_schema, m_definitions, nested_models = model_type_schema(
    ../venv/lib/python3.8/site-packages/pydantic/schema.py:566: in model_type_schema
        f_schema, f_definitions, f_nested_models = field_schema(
    ../venv/lib/python3.8/site-packages/pydantic/schema.py:222: in field_schema
        f_schema, f_definitions, f_nested_models = field_type_schema(
    ../venv/lib/python3.8/site-packages/pydantic/schema.py:475: in field_type_schema
        assert field.shape == SHAPE_SINGLETON, field.shape
    E   AssertionError: 10
'''
```
(This script should run as-is.)

Will be most interested in any pointers or hints of what I might be doing wrong. Thank you.

**Comment by daviskirk** [comment]
Could you try this out on master and 1.8.1 and see if this might already be fixed?
There were a lot of fixes regarding generics since 1.7.3 (the version your using).

**Comment by anatoly-scherbakov** [comment]
Thank you! I will try this out.

**Comment by Forever-Young** [comment]
Updating to 1.8.2 didn't help:

```
Pydantic version: 1.8.2
Traceback (most recent call last):
  File "tests/test.py", line 46, in <module>
    model_schema(CatsQuery)
  File "pydantic/schema.py", line 167, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 515, in pydantic.schema.field_type_schema
  File "tests/test.py", line 36, in __modify_schema__
    raise ValueError('I am not even called! :(')
ValueError: I am not even called! :(
```

**Comment by Forever-Young** [comment]
Final working solution:

```
ContainerType = TypeVar('ContainerType')


# `str` here gives correct openapi definition
class CommaSeparatedSet(str, Generic[ContainerType]):
    """Comma separated values of a container."""

    @classmethod
    def __get_validators__(cls):
        """Ensure pydantic compatibility."""
        yield cls.validate

    @classmethod
    def validate(cls, raw_value: str, field: ModelField) -> Set[ContainerType]:
        """Validate the raw value."""
        field_type = field.type_.__orig_bases__[0].__args__[0]
        if isinstance(raw_value, str):
            return set(map(
                field_type,
                raw_value.split(','),
            ))
        return raw_value


# inheritance makes __orig_bases__ magic work
class CommaSeparatedSetOfColors(CommaSeparatedSet[Color]):
    pass


class CatsQuery(BaseModel):
    """Query our cats herd."""

    color__in: Optional[CommaSeparatedSetOfColors]] = None
```

Maybe there's a way to get `field_type` without inheritance?

**Comment by hramezani** [comment]
@anatoly-scherbakov Please test your example in `Pydantic V2`. It's in alpha state and you can install it by `pip install pydantic --pre`.

Please report a new issue on `V2` if you still have a problem. I close this one.

I changed your example in `V2` and it raises `ValueError: I am not even called! :(`:
```py
from enum import Enum
from typing import Optional, Generic, TypeVar, Set

from pydantic import BaseModel, ConfigDict, version
from pydantic.fields import Field

ContainerType = TypeVar('ContainerType')


class Color(str, Enum):
    """Cat colors."""

    RED = 'red'
    WHITE = 'white'
    BLACK = 'black'


class CommaSeparated(Generic[ContainerType]):
    """Comma separated values of a container."""

    @classmethod
    def __get_validators__(cls):
        """Ensure pydantic compatibility."""
        yield cls.validate

    @classmethod
    def validate(cls, raw_value: str, field: Field) -> ContainerType:
        """Validate the raw value."""
        raise ValueError(
            'I will write this validation later, too lazy right now :(',
        )

    @classmethod
    def __pydantic_modify_json_schema__(cls, field_schema):
        raise ValueError('I am not even called! :(')


class CatsQuery(BaseModel):
    """Query our cats herd."""

    color__in: Optional[CommaSeparated[Set[Color]]] = None

    model_config = ConfigDict(arbitrary_types_allowed=True)


print(f'Pydantic version: {version.VERSION}')
CatsQuery.model_json_schema()
```

**Comment by dmontagu** [comment]
This will need modifications to work in v2 but there is at least one test showing how to create a custom generic type in v2: https://github.com/pydantic/pydantic/blob/c600c010418c46cec1f3a0fe8fb6ca4be4a7949f/tests/test_edge_cases.py#LL1877C5-L1877C17
