### ISSUE TITLE
Hitting  `Fields of type "<class 'types.Union'>" are not supported` in Python 3.10.0a6 when using the ' | ' for Union in annotating field types.

### ISSUE THREAD

**Issue by donato-clumio** [samuelcolvin/pydantic#2607]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
I'm hitting  `Fields of type "<class 'types.Union'>" are not supported` in Python 3.10.0a6 when using the ' | ' for Union in annotating field types. However, when I use the `Union` annotation for field types, it works:

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: False
                 install path: /home/donato/.pyenv/versions/3.10.0a6/envs/py3_10a6/lib/python3.10/site-packages/pydantic
               python version: 3.10.0a6 (default, Mar 30 2021, 12:26:09) [GCC 9.3.0]
                     platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

```
Python 3.10.0a6 (default, Mar 30 2021, 12:26:09) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydantic
>>> from typing import Union
>>> class TestB(pydantic.BaseModel):
...   f1: Union[str, None]
...   f2: Union[int, None]
...
>>> t1 = TestB()
>>> t1
TestB(f1=None, f2=None)
>>> class TestC(pydantic.BaseModel):
...   f1: str | None
...   f2: int | None
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/donato/.pyenv/versions/py3_10a6/lib/python3.10/site-packages/pydantic/main.py", line 293, in __new__
    fields[ann_name] = ModelField.infer(
  File "/home/donato/.pyenv/versions/py3_10a6/lib/python3.10/site-packages/pydantic/fields.py", line 410, in infer
    return cls(
  File "/home/donato/.pyenv/versions/py3_10a6/lib/python3.10/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/home/donato/.pyenv/versions/py3_10a6/lib/python3.10/site-packages/pydantic/fields.py", line 450, in prepare
    self._type_analysis()
  File "/home/donato/.pyenv/versions/py3_10a6/lib/python3.10/site-packages/pydantic/fields.py", line 626, in _type_analysis
    raise TypeError(f'Fields of type "{origin}" are not supported.')
TypeError: Fields of type "<class 'types.Union'>" are not supported.
>>>
```

**Comment by PrettyWood** [comment]
Hi @donato-clumio 
Yes `|` has not the same origin. It's `types.Union` and not `typing.Union`, which is not supported in pydantic.
But 3.10 won't be supported in v1 I reckon since a lot needs to be tackled to also handle properly forward refs, which is the new default in 3.10.
Wait for v2! 👍 😄

**Comment by donato-clumio** [comment]
@PrettyWood Thanks for update. I didn't notice the `types.Union` as distinct from `typing.Union`. Will wait for v2 then.
