### ISSUE TITLE
Pydantic 1.8.0 raises Exception when overriding __eq__

### ISSUE THREAD

**Issue by kosciej16** [samuelcolvin/pydantic#2639]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

```py
from pydantic import BaseModel


class Foo(BaseModel):
    value: int

    def __eq__(self, other):
        return self.value == other.value


class Test(BaseModel):
    foo: Foo = Foo(value=10)
```
for pydantic 1.7.x it works.
when 1.8.1 it raises:
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    class Test(BaseModel):
  File "pydantic/main.py", line 287, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 384, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 369, in pydantic.fields.ModelField._get_field_info
  File "pydantic/fields.py", line 157, in pydantic.fields.FieldInfo._validate
  File "main.py", line 8, in __eq__
    return self.value < other.value
AttributeError: 'UndefinedType' object has no attribute 'value'
```

**Comment by PrettyWood** [comment]
Hi @kosciej16 
https://github.com/samuelcolvin/pydantic/pull/2502 is already open :)

**Comment by kosciej16** [comment]
@PrettyWood Thanks for letting me know but I see this PR is quite old, can I somehow help with closing it?
