### ISSUE TITLE
Using BaseModel with functools.cached_property raises "TypeError: cannot pickle '_thread.RLock' object"

### ISSUE THREAD

**Issue by rahul-raturi** [samuelcolvin/pydantic#2763]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/rraturi/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
                     platform: Linux-5.4.0-73-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

## Code snippet
```py
from pydantic import BaseModel
from functools import cached_property

class TestCached(BaseModel):
    number: int

    @cached_property
    def squared(self):
        return self.number ** 2

instance = TestCached(number=4)
print(instance.squared)
```
## Stack trace
```
Traceback (most recent call last):
  File "script.py", line 4, in <module>
    class TestCached(BaseModel):
  File "pydantic/main.py", line 317, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 410, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 444, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 473, in pydantic.fields.ModelField._set_default_and_type
  File "pydantic/fields.py", line 345, in pydantic.fields.ModelField.get_default
  File "pydantic/utils.py", line 630, in pydantic.utils.smart_deepcopy
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object
```

**Comment by rahul-raturi** [comment]
There's a similar issue here: https://github.com/samuelcolvin/pydantic/issues/1241
I reported this as the error is different.

The fix mentioned in the other PR works though:
```py
from pydantic import BaseModel
from functools import cached_property

class TestCached(BaseModel):
    number: int

    @cached_property
    def squared(self):
        return self.number ** 2

    class Config:
        keep_untouched = (cached_property,)

instance = TestCached(number=4)
print(instance.squared)
```

**Comment by samuelcolvin** [comment]
`cached_property` is not supported, so as far as I'm concerned this is effectively the same as #1241.
