### ISSUE TITLE
underscore_attrs_are_private not considerate with keep_untouched

### ISSUE THREAD

**Issue by a5r0n** [samuelcolvin/pydantic#3028]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: .venv/lib64/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, May  4 2021, 00:00:00)  [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
                     platform: Linux-5.11.22-100.fc32.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
...
```

keep_untouched shouldn’t override underscore_attrs_are_private..
some workaround is just use json(`exclude_unset=True`)..

```py
from pydantic import BaseModel
from functools import cached_property

class CustomType:
    pass

class Cow(BaseModel):
    #...
    @cached_property
    def _client(self):
        """not json serializable"""
        return CustomType()
    class Config:
        underscore_attrs_are_private = True
        keep_untouched = (cached_property,)

>>> cow = Cow()
>>> cow.json()
'{}'
>>> type(cow._client)
<class '__main__.CustomType'>
>>> cow.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 557, in pydantic.main.BaseModel.json
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 95, in pydantic.json.pydantic_encoder
TypeError: Object of type 'CustomType' is not JSON serializable
>>> 
```

**Comment by PrettyWood** [comment]
Hi @a5r0n 
Yup but in fact `_client` is not an attr! So `underscore_attrs_are_private` doesn't even apply.
Your problem should be solved with #2625

```py
    @computed_field(exclude=True)
    @cached_property
    def _client(self):
        """not json serializable"""
        return CustomType()
```
