### ISSUE TITLE
Error when using nested BaseSettings classes

### ISSUE THREAD

**Issue by kobiche** [samuelcolvin/pydantic#3115]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: C:\Users\ricardoch\VirtualEnv\fastapi\Lib\site-packages\pydantic
               python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
import pydantic
from pydantic import BaseSettings


class PostgresSettings(BaseSettings):
    USER: str
    PASSWORD: str
    HOST: str
    PORT: int
    DB: str

    class Config:
        env_prefix = "POSTGRES_"


class Settings(BaseSettings):
    POSTGRES: PostgresSettings
    PROJECT_NAME: str
    FASTAPI_ENV: str
    TESTING: bool = False

    class Config:
        case_sensitive = True

settings = Settings(_env_file='settings.env')
print(settings)
```

produces following error
```
Traceback (most recent call last):
  File "...", line 42, in <module>
    settings = Settings(_env_file='settings.env')
  File "pydantic\env_settings.py", line 36, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
POSTGRES
  field required (type=value_error.missing)
```

It seems that the sub-class PostgresSettings(...) does not read the '.env' file.
It works however if I define it like this

```
class Settings(BaseSettings):
    POSTGRES: PostgresSettings = PostgresSettings(_env_file='settings.env')
    PROJECT_NAME: str
    FASTAPI_ENV: str
    TESTING: bool = False

    class Config:
        case_sensitive = True
```

Here is my 'settings.env' sample
```
POSTGRES_USER=qwe
POSTGRES_PASSWORD=asd
POSTGRES_HOST=zxc
POSTGRES_PORT=000
POSTGRES_DB=iupo

PROJECT_NAME=hello
FASTAPI_ENV=there
TESTING=true
```

**Comment by aminalaee** [comment]
Your .env file I think should be modified:

```bash
POSTGRES='{"USER": "", "PASSWORD": "", "HOST": "", "DB": "", "PORT": 5432}'
PROJECT_NAME =A
FASTAPI_ENV =B
TESTING=False
```

You can check the docs: https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values

**Comment by samuelcolvin** [comment]
Or use a double underscore when defining nested variables.

https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values
