### ISSUE TITLE
passing `max_items` in `Field` with a `List[Literal["something"]` field raises `TypeError`

### ISSUE THREAD

**Issue by Pedrexus** [samuelcolvin/pydantic#3119]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: True
install path: /home/ubuntu/.local/lib/python3.8/site-packages/pydantic
python version: 3.8.5 (default, May 27 2021, 13:30:53)  [GCC 9.3.0]
platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
optional deps. installed: ['typing-extensions']
```

passing `max_items` raises an error only when the field type is `List[Literal["something"]`.

expectation: passing `max_items` would not raise an error or would raise a more readable error

```py
Python 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel, Field
>>> from typing import List, Literal
>>> class MyModel(BaseModel):
...     it: List[Literal["hi", "hello"]] = Field(max_items=2)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 410, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 920, in pydantic.schema.get_annotation_from_field_info
  File "pydantic/schema.py", line 1015, in pydantic.schema.get_annotation_with_constraints
  File "pydantic/schema.py", line 967, in pydantic.schema.get_annotation_with_constraints.go
  File "pydantic/schema.py", line 965, in pydantic.schema.get_annotation_with_constraints.go
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

>>> class MyModel(BaseModel):
...     it: List[Literal["hi", "hello"]] = Field(description="here")
...

>>> class MyModel(BaseModel):
...     it: List[str] = Field(max_items=2)
...
```

Thanks for all help and the work you are doing with this library. We truly appreciate it.

**Comment by PrettyWood** [comment]
Hi @Pedrexus 
Already solved by https://github.com/samuelcolvin/pydantic/pull/2794
Thanks for reporting!
