### ISSUE TITLE
create_model with fields using Field and default_factory fails due to missing field type

### ISSUE THREAD

**Issue by christopherpole-cs** [samuelcolvin/pydantic#3184]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/<snip>/Documents/virtual-environments/<snip>/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, May  4 2021, 03:36:27)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-11.4-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'typing-extensions']

```
searched for instances of create_model in open issues and none looked like they matched.

Example of issue:

```py
import pydantic

countries = ['us', 'nz', 'au']

class Child(pydantic.BaseModel):
    score: float = 0

Parent = pydantic.create_model(
    'Parent',
    **{cc: pydantic.Field(default_factory=Child) for cc in countries},
)

test = Parent()
```

results in:
```
Traceback (most recent call last):
  File "<input>", line 8, in <module>
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 323, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 445, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 467, in pydantic.fields.ModelField._set_default_and_type
pydantic.errors.ConfigError: you need to set the type of field 'us' when using `default_factory`
```

the create_model doc string suggests this code should work:

```
:param field_definitions: fields of the model (or extra fields if a base is supplied)
    in the format `<name>=(<type>, <default default>)` or `<name>=<default value>, e.g.
    `foobar=(str, ...)` or `foobar=123`, or, for complex use-cases, in the format
    `<name>=<FieldInfo>`, e.g. `foo=Field(default_factory=datetime.utcnow, alias='bar')`
```

```py
from datetime import datetime
import pydantic

Test = pydantic.create_model(
    'Test',
    xxx=pydantic.Field(default_factory=datetime.utcnow)
)

test = Test()
```

however this also results in:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 323, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 445, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 467, in pydantic.fields.ModelField._set_default_and_type
pydantic.errors.ConfigError: you need to set the type of field 'xxx' when using `default_factory`
```

**Comment by christopherpole-cs** [comment]
Misunderstood documentation, turns out the following works:

```py
import pydantic

countries = ['us', 'nz', 'au']

class Child(pydantic.BaseModel):
    score: float = 0

Parent = pydantic.create_model(
    'Parent',
    **{cc: (Child, pydantic.Field(default_factory=Child)) for cc in countries},
)

test = Parent()
```

**Comment by kalzoo** [comment]
[This](https://github.com/samuelcolvin/pydantic/blob/18e1361e8b8347fee9cfbbba94f6c0220bced418/pydantic/main.py) line in the docs appears incorrect the way I read it, and is in line with your initial report. Looks like that could use a fix?
