### ISSUE TITLE
Spurious import from current working directory

### ISSUE THREAD

**Issue by luizfelippesr** [samuelcolvin/pydantic#3275]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /opt/conda/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0]
                     platform: Linux-5.4.0-1049-azure-x86_64-with-glibc2.10
     optional deps. installed: ['typing-extensions']
```

I was working on a project which happened to have a file named `inspect.py`. I realised that when I imported pydantic, it tried to read that file if it was in the current working directory. The following should reproduce the behaviour I encountered:

```bash
echo "print('Is this a bug?')" > inspect.py; python -c "import pydantic"
```
Output
```
Is this a bug?
Exception ignored in: <module 'inspect' from '/home/jovyan/test/inspect.py'>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'inspect' has no attribute 'isgenerator'
<frozen importlib._bootstrap>:219: RuntimeWarning: Cython module failed to patch module with custom type
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 7, in init pydantic.dataclasses
    import builtins
  File "pydantic/main.py", line 376, in init pydantic.main
  File "pydantic/main.py", line 345, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/class_validators.py", line 194, in pydantic.class_validators.extract_root_validators
ImportError: cannot import name signature
```

**Comment by luizfelippesr** [comment]
Now I realise that this bug is invalid.
