### ISSUE TITLE
change ValidationError.errors()

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#337]
The `errors()` function should change its signature to `errors(full=False)`. With `full=True` the output should be the same as present.

With `full=False`, the output should be simplied to:
* `loc` should be a dot delimited string
* `ctx` should be removed. 

So with `full=True`:
```py
[
    {
        'loc': ('b',),
        'msg': 'ensure this value has at least 1 characters',
        'type': 'value_error.any_str.min_length',
        'ctx': {'limit_value': 1},
    }
]
```

with `full=False`:
```
[
    {
        'loc': 'b',
        'msg': 'ensure this value has at least 1 characters',
        'type': 'value_error.any_str.min_length',
    }
]
```

Feedback welcome, otherwise i'll do before the next release.

**Comment by Gr1N** [comment]
Can you please describe why you want to change current behavior? Plus as I remember, decision to return `loc` as tuple was yours :) And it's a backward incompatible change...

**Comment by samuelcolvin** [comment]
> Can you please describe why you want to change current behavior? 

Because I think it will be more elegant and easier for new users. Plus in most cases `ctx` is completely irrelevant, it really shouldn't be in the public API.

> Plus as I remember, decision to return loc as tuple was yours :) 

Yes, it was a mistake, I've been regretting it since.

> And it's a backward incompatible change...

I know, but we should aim to get it right and not be afraid of breaking changes.

**Comment by Gr1N** [comment]
Understand, just one moment, dot delimited string isn't good, because of possible dots in dict keys:
```
➜ python
Python 3.7.1 (default, Nov  6 2018, 18:46:03)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel
>>> from typing import Dict
>>> class Model(BaseModel):
...     k: Dict[str, int]
...
>>> Model.parse_obj({'k': {'a.b.c': 'd'}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ng/.virtualenvs/tmp-5e251d8d098bcac/lib/python3.7/site-packages/pydantic/main.py", line 262, in parse_obj
    return cls(**obj)
  File "/Users/ng/.virtualenvs/tmp-5e251d8d098bcac/lib/python3.7/site-packages/pydantic/main.py", line 190, in __init__
    self.__setstate__(self._process_values(data))
  File "/Users/ng/.virtualenvs/tmp-5e251d8d098bcac/lib/python3.7/site-packages/pydantic/main.py", line 360, in _process_values
    return validate_model(self, input_data)
  File "/Users/ng/.virtualenvs/tmp-5e251d8d098bcac/lib/python3.7/site-packages/pydantic/main.py", line 533, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
k -> a.b.c
  value is not a valid integer (type=type_error.integer)
>>>
```
