### ISSUE TITLE
model.schema() crashes on models with with type Type[...]

### ISSUE THREAD

**Issue by ofercaspi** [samuelcolvin/pydantic#3390]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Any model that includes a `Type` or `Type[...]` typed field, crashes on the schema() method.
This reproduction is based on [the example in the docs](https://pydantic-docs.helpmanual.io/usage/types/#type), only with the added call to schema():
```python
from typing import Type
from pydantic import BaseModel

class LenientSimpleModel(BaseModel):
    any_class_goes: Type

my_model = LenientSimpleModel(any_class_goes=int)
my_model.schema()
```
Traceback:
```
.../site-packages/pydantic/main.cpython-38-darwin.so in pydantic.main.BaseModel.schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.model_schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.model_process_schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.model_type_schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.field_schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.field_type_schema()
.../site-packages/pydantic/schema.cpython-38-darwin.so in pydantic.schema.field_singleton_schema()

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/abc.py in __subclasscheck__(cls, subclass)
    100         def __subclasscheck__(cls, subclass):
    101             """Override for issubclass(subclass, cls)."""
--> 102             return _abc_subclasscheck(cls, subclass)
    103
    104         def _dump_registry(cls, file=None):

TypeError: issubclass() arg 1 must be a class
```
I'm on python==3.8.7, pydantic==1.8.2, on MacOS 11.3.1

Am I missing something, or is this a real bug?

**Comment by al-dpopowich** [comment]
I'm having this same problem.  In my application I have a pydantic model that expects a subclass of `AppModel` which is very reproducible with any type reference:

```python
from typing import Type
from pydantic import BaseModel
from myapp import AppModel

class ModelRef(BaseModel):
   cls: Type[AppModel]

ModelRef.schema()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 710, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 167, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 241, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 495, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 839, in pydantic.schema.field_singleton_schema
  File "/usr/local/lib/python3.9/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
