### ISSUE TITLE
`Field(discriminator=...)` fails if `Union` has only one option.

### ISSUE THREAD

**Issue by jonathanslenders** [samuelcolvin/pydantic#3550]
### Checks

If there is only one option in the ``Union``, somehow Pydantic thinks it's no longer a ``Union`` and the ``discriminator`` option is no longer allowed.

Maybe this is by design, but it gets confusing after commenting out an option from the union. It would be good, if if the ``Union`` remains a ``Union``, even if there is only one item inside.

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0a1
            pydantic compiled: True
                 install path: /home/jonathan/.pyenv/versions/3.9.5/envs/lazy-maestro/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Jun  3 2021, 16:26:08)  [GCC 9.3.0]
                     platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py
from typing import Union
from pydantic import Field, BaseModel
from typing_extensions import Literal

class Option1(BaseModel):
    type: Literal["option1"]

class Container(BaseModel):
    result: Union[Option1] = Field(discriminator="type")
```

The traceback:
```
Traceback (most recent call last):
  File "/tmp/test2.py", line 12, in <module>
    class Container(BaseModel):
  File "pydantic/main.py", line 203, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 487, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 418, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 533, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 602, in pydantic.fields.ModelField._type_analysis
TypeError: `discriminator` can only be used with `Union` type
```

**Comment by PrettyWood** [comment]
Hi @jonathanslenders 
Unfortunately we can't do anything about it because of how `Union[X]` is interpreted
```py
from typing import Union

class Option1: ...

x = Union[Option1]

assert x is Option1
```
So at runtime we have no way to know it was a `Union`

**Comment by jonathanslenders** [comment]
No problem. I understand!
