### ISSUE TITLE
get_args returns empty tuple when used with GenericModel

### ISSUE THREAD

**Issue by mrabiciu** [samuelcolvin/pydantic#3559]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: <PATH_TO_VENV>/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Aug 10 2021, 11:25:09)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

# Description

I'm trying to run some custom validation on the generic arguments of a `GenericModel`. However I am unable to inspect the generic arguments using `typing.get_args` 

```py
from pydantic.generics import GenericModel
from typing import Generic, TypeVar, get_args

T = TypeVar('T')
class Model(GenericModel, Generic[T]):
    foo: T

print(get_args(Model[str]))
```
Expected output: 
```
(<class 'str'>,)
```
Actual output: 
```
()
```

This only happens when inheriting from `GenericModel`. If I don't inherit from `GenericModel` I get the expected output
```py
class WithoutGenericModel(Generic[T]):
    foo: T

print(get_args(WithoutGenericModel[str]))
```
Output
```
(<class 'str'>,)
```

I also get the expected output if I inherit from `BaseModel` instead of `GenericModel`
```py
class JustBaseModel(BaseModel, Generic[T]):
    foo: T

print(get_args(JustBaseModel[str]))
```
Output
```
(<class 'str'>,)
```

I'm following the [official documentation for creating generic models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
Am I doing something wrong here? I see there are references to `get_args` in generics.py so my expectation is that this should work like it does for other types.
I did a little more digging and it seems like 
```py
isinstance(Model[str], _GenericAlias)
```
fails and `Model[str]` doesn't have an attribute named `__params__`

**Comment by tbsexton** [comment]
I just ran into this myself, as well

**Comment by mdelmans** [comment]
Is there any progress on this one ?
Is there an alternative way how to get args ?

**Comment by eigenein** [comment]
It seems I have found a workaround. The idea is to override `__class_getitem__` to access the original type parameters:

```python
class Foo(GenericModel, …):
    __store_original_params_here__: ClassVar[Tuple[Type[Any]]]

    def __class_getitem__(cls, params: Union[Type[Any], Tuple[Type[Any], ...]]) -> Type[Any]:
        if not isinstance(params, tuple):
            params = (params,)
        model: Type[Any] = super().__class_getitem__(params)
        model.__store_original_params_here__ = params
        return model
```

**Comment by eigenein** [comment]
If a model actually got a `TypeVar`-typed field, then probably the easiest way is just to inspect the `__fields__`:

```python
>>> Child[bool].__fields__["s"].type_
<class 'bool'>
```

And it also works for grandchildren, which is cool. Now the question is, what if the model doesn't have any field annotated with the `TypeVar`…

**Comment by haoyun** [comment]
> ```python
> >>> Child[bool].__fields__["s"].type_
> <class 'bool'>
> ```

I found this useful. For those who are using Pydantic v2, the following will work:

```python
>>> Child[bool].model_fields["s"].annotation
<class 'bool'>
```

**Comment by ar45** [comment]
looks like `__pydantic_generic_metadata__` has the info

```
from typing import *
from pydantic import *
T1 = TypeVar('T1')
class ABCModel(BaseModel, Generic[T1]):
    f1: str
    
ABCModel.__pydantic_generic_metadata__
{'origin': None, 'args': (), 'parameters': (~T1,)}
ABCModel[str].__pydantic_generic_metadata__
{'origin': <class '__main__.ABCModel'>, 'args': (<class 'str'>,), 'parameters': ()}
```

**Comment by ariofrio** [comment]
> looks like `__pydantic_generic_metadata__` has the info

Is there an equivalent for Pydantic v1, to use when there is no TypeVar-typed field?

**Comment by ariofrio** [comment]
I found this hack:

```
from pydantic import v1
from pydantic.v1 import generics as v1_generics

_T = TypeVar("_T", bound=BaseModel)

class MyModel(v1_generics.GenericModel, Generic[_T])
    @classmethod
    def get_type_arg(cls):
        return v1_generics._assigned_parameters[cls][_T]
```

**Comment by eldadcool** [comment]
> looks like `__pydantic_generic_metadata__` has the info
> 
> ```
> from typing import *
> from pydantic import *
> T1 = TypeVar('T1')
> class ABCModel(BaseModel, Generic[T1]):
>     f1: str
>     
> ABCModel.__pydantic_generic_metadata__
> {'origin': None, 'args': (), 'parameters': (~T1,)}
> ABCModel[str].__pydantic_generic_metadata__
> {'origin': <class '__main__.ABCModel'>, 'args': (<class 'str'>,), 'parameters': ()}
> ```

Also found this hack but it because it uses an internal structure I cannot relay on it not being changed in the future.

Is there a plan to standardize it to expose the generic args to an external api function so I can get it in a standardized way?

**Comment by sisp** [comment]
The hack based on `<Model>.__pydantic_generic_metadata__` doesn't work on non-generic child models though:

```python
from typing import *
from pydantic import *
T1 = TypeVar('T1')
class ABCModel(BaseModel, Generic[T1]):
    f1: str
class Child(ABCModel[int]):
    ...
    
ABCModel.__pydantic_generic_metadata__
# {'origin': None, 'args': (), 'parameters': (~T1,)}
ABCModel[str].__pydantic_generic_metadata__
# {'origin': <class '__main__.ABCModel'>, 'args': (<class 'str'>,), 'parameters': ()}
Child.__pydantic_generic_metadata__
# {'origin': None, 'args': (), 'parameters': ()}
```

I'm trying to access a generic type in a base class method, and non-generic child classes shall be able to call that method with the type variable from the base class:

```python
from typing import Generic, TypeVar
from pydantic import BaseModel, TypeAdapter


T = TypeVar("T")

class Base(BaseModel, Generic[T]):
    def parse(self, value: Any) -> T:
        return TypeAdapter(self.__pydantic_generic_metadata__["args"][0]).validate_python(value)


class Child(Base[int]):
    ...


Base[int]().parse("123")
# 123

Child().parse("123")
# Traceback (most recent call last):
#   File "...", line 19, in <module>
#     Child().parse("123")
#     ~~~~~~~~~~~~~^^^^^^^
#   File "...", line 9, in parse
#     return TypeAdapter(self.__pydantic_generic_metadata__["args"][0]).validate_python(value)
#                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
# IndexError: tuple index out of range
```

Has anybody come up with a solution to this problem? 🤔

**Comment by laurierloi** [comment]
@sisp I found a workaround by inspecting mro:

```python
Child.__mro__[1].__pydantic_generic_metadata__['args'][0]
```

There's probably some validation that can be done by looping through the mro and validating that the `__pydantic_generic_metadata__['origin'] is not None`.

For my use case, the order is constant so I didn't have to go through that.

This is obviously very brittle...
