### ISSUE TITLE
GenericModel does not mix well with ABC

### ISSUE THREAD

**Issue by mrabiciu** [samuelcolvin/pydantic#3802]
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /PATH_TO_VENV/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Aug 10 2021, 11:25:09)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Base classes that inherit from `GenericModel` don't seem to mix well with `ABC` and can lead to confusing validation errors
```py
from pydantic import BaseModel
from pydantic.generics import GenericModel
from typing import Generic, TypeVar
from abc import ABC, abstractmethod

T = TypeVar('T')

class BaseClass(GenericModel, Generic[T], ABC):
    argument: T

    @abstractmethod
    def some_abstract_method(self) -> str:
        pass

class ChildClass(BaseClass[T], Generic[T]):
    other_argument: T

    def some_abstract_method(self) -> str:
        return "some value"


class Container(BaseModel):
    content: BaseClass[str]

container = Container(
    content=ChildClass(argument="action", other_argument="other_action")
)
```
### Expectation:
Executes successfully

### Result
```
Traceback (most recent call last):
  File "pydantic_abc_generics_test.py", line 25, in <module>
    container = Container(
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Container
content
  Can't instantiate abstract class BaseClass[str] with abstract methods some_abstract_method (type=type_error)
```
It seems like somehow `ChildClass` is being turned into its base `BaseClass` 

I'm able to work around this issue by adding explicit type parameters when instantiating `ChildClass`
```py
container = Container(
    content=ChildClass[str](argument="action", other_argument="other_action")
)
```
However the validation error makes it very unclear that this would fix the issue. The mypy plugin also doesn't seem to offer the ability to enforce that explicit type parameters are supplied like this.

This issue also does not occur if I use BaseModel instead of GenericModel which makes me think this is a bug with `GenericModel`
```py
from pydantic import BaseModel
from abc import ABC, abstractmethod

class BaseClass(BaseModel, ABC):
    argument: str

    @abstractmethod
    def some_abstract_method(self) -> str:
        pass

class ChildClass(BaseModel):
    other_argument: str

    def some_abstract_method(self) -> str:
        return "some value"


class Container(BaseModel):
    content: BaseClass

container = Container(
    content=ChildClass(argument="action", other_argument="other_action")
)
```

**Comment by lig** [comment]
@mrabiciu thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
