### ISSUE TITLE
Using default_factory for Annotated[Union[...], Field(default_factory=...)] prevents using default_factory for collections containing  that type

### ISSUE THREAD

**Issue by TueVJ** [samuelcolvin/pydantic#3804]
### Checks

* [ x ] I added a descriptive title to this issue
* [ x ] I have searched (google, github) for similar issues and couldn't find anything
* [ x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Trying to run the script below produces this error, tested for both for pydantic 1.8.2 and 1.9.0:

```
Traceback (most recent call last):
  File "/[snip]i/temp.py", line 31, in <module>
    class LetterHolder2(BaseModel):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 776, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 464, in pydantic.fields.ModelField._get_field_info
  File "pydantic/fields.py", line 211, in pydantic.fields.FieldInfo._validate
ValueError: cannot specify both default and default_factory
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`: (Also tested for 1.8.2)
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/USER/.cache/pypoetry/virtualenvs/temp-project-jzM_oSD3-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (main, Jan 15 2022, 18:17:56)  [GCC 9.3.0]
                     platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

```py
from typing import Literal, Annotated, Union, Dict

from pydantic import BaseModel, Field


class A(BaseModel):
    letter_type: Literal["A"] = "A"


class B(BaseModel):
    letter_type: Literal["B"] = "B"


Letter1 = Annotated[Union[A, B], Field(discriminator="letter_type")]


# This definition works
class LetterHolder1(BaseModel):
    mapping_to_letter: Dict[str, Letter1] = Field(default_factory=dict)


def default_constructor() -> A:
    """Default constructor for letters."""
    return A()


Letter2 = Annotated[Union[A, B], Field(discriminator="letter_type", default_factory=default_constructor)]


# This definition does not work
class LetterHolder2(BaseModel):
    mapping_to_letter: Dict[str, Letter2] = Field(default_factory=dict)

# Neither does this one
class LetterHolder3(BaseModel):
    mapping_to_letter: List[Letter2] = Field(default_factory=list)

```

**Comment by TueVJ** [comment]
Possibly related to #3702
