### ISSUE TITLE
SecretStr - Passlib Compatibility

### ISSUE THREAD

**Issue by jteppinette** [samuelcolvin/pydantic#3827]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: True
install path: /<project-dir>/.direnv/python-3.10.2/lib/python3.10/site-packages/pydantic
python version: 3.10.2 (main, Feb 16 2022, 17:47:34) [Clang 12.0.5 (clang-1205.0.22.11)]
platform: macOS-11.5.2-x86_64-i386-64bit
optional deps. installed: ['email-validator', 'typing-extensions']
```

```py
from passlib.context import CryptContext
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
from pydantic import BaseModel, SecretStr
class Form(BaseModel):
    password: SecretStr

f = Form(password="test")
hash = pwd_context.hash("test")
pwd_context.verify(f.password, hash)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jteppinette/Software/protex-api/.direnv/python-3.10.2/lib/python3.10/site-packages/passlib/context.py", line 2347, in verify
    return record.verify(secret, hash, **kwds)
  File "/Users/jteppinette/Software/protex-api/.direnv/python-3.10.2/lib/python3.10/site-packages/passlib/utils/handlers.py", line 787, in verify
    validate_secret(secret)
  File "/Users/jteppinette/Software/protex-api/.direnv/python-3.10.2/lib/python3.10/site-packages/passlib/utils/handlers.py", line 122, in validate_secret
    raise exc.ExpectedStringError(secret, "secret")
TypeError: secret must be unicode or bytes, not pydantic.types.SecretStr
```

**Comment by jteppinette** [comment]
I guess this is my bad. You need to run `.get_secret_value()` to retrieve the original string.
