### ISSUE TITLE
Edge Case: class gets changed on pydantic objects __init__

### ISSUE THREAD

**Issue by tmonster94** [samuelcolvin/pydantic#3880]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I have made a minimal example based on a problem encountered my codebase at work. I make explicit classes `AddOperation`, `SetOperation`, and `RemoveOperation`. But when putting them in a wrapper model they are all changed to `AddOperation` because they are structurally the same (except for the Aliases).

_requirements.txt_
```
pydantic == 1.9.0
```

_example_minimal.py_
```py
import json

from typing import List, Union
from pydantic import BaseModel, Field

class FieldNameBaseModel(BaseModel):
    class Config:
        allow_population_by_field_name = True

class AddOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="AddOperationId")

class SetOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="SetOperationId")

class RemoveOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="RemoveOperationId")

class BulkOperations(FieldNameBaseModel):
    bulk_operations: List[
        Union[
            AddOperation,
            SetOperation,
            RemoveOperation,
        ]
    ] = Field(..., alias="BulkOperations")


def main():

    add_operation = AddOperation(operation_id="item-add")
    set_operation = SetOperation(operation_id="item-set")
    remove_operation = RemoveOperation(operation_id="item-remove")

    bulk_operations = [add_operation, set_operation, remove_operation]

    direct_instantiation = BulkOperations(bulk_operations=bulk_operations)
    direct_json = direct_instantiation.json(by_alias=True)

    parse_obj_version = BulkOperations.parse_obj(
        {"bulk_operations": [x.dict(by_alias=True) for x in bulk_operations]}
    )
    parsed_json = parse_obj_version.json(by_alias=True)

    print(
        "Direct Method:",
        direct_instantiation,
        "\n->",
        direct_json,
        "\n",
    )
    print(
        "Parsed Method:",
        parse_obj_version,
        "\n->",
        parsed_json,
        "\n",
    )

    assert direct_json == parsed_json


if __name__ == "__main__":
    main()
```

_output of example_minimal.py_
```
Direct Method: bulk_operations=[AddOperation(operation_id='item-add'), AddOperation(operation_id='item-set'), AddOperation(operation_id='item-remove')] 
-> {"BulkOperations": [{"AddOperationId": "item-add"}, {"AddOperationId": "item-set"}, {"AddOperationId": "item-remove"}]} 

Parsed Method: bulk_operations=[AddOperation(operation_id='item-add'), SetOperation(operation_id='item-set'), RemoveOperation(operation_id='item-remove')] 
-> {"BulkOperations": [{"AddOperationId": "item-add"}, {"SetOperationId": "item-set"}, {"RemoveOperationId": "item-remove"}]} 

Traceback (most recent call last):
  File "example_minimal.py", line 69, in <module>
    main()
  File "example_minimal.py", line 65, in main
    assert direct_json == parsed_json
AssertionError
```

# Thoughts

This seems to be related to the use of `allow_population_by_field_name = True`, my three models have the same exact structure. Which means that the first one of the union is taken.
```py
class AddOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="AddOperationId")

class SetOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="SetOperationId")

class RemoveOperation(FieldNameBaseModel):
    operation_id: str = Field(..., alias="RemoveOperationId")
 ```
 
 For me, it was unexpected that when I pass in a `RemoveOperation` it gets changed to an `AddOperation`. 
 
I understand this is very much an edge case but I encountered it because I use the same models to parse incoming json (and xml), and construct json to interact with an api.

Another thing we did in our codebase to work around it was to change the structure of the objects, but this makes it a lot less convenient to work with incoming data:

```py
class AddOperation(FieldNameBaseModel):
    add_operation_id: str = Field(..., alias="AddOperationId")

class SetOperation(FieldNameBaseModel):
    set_operation_id: str = Field(..., alias="SetOperationId")

class RemoveOperation(FieldNameBaseModel):
    remove_operation_id: str = Field(..., alias="RemoveOperationId")
 ```

So my question is, should something change about how `allow_population_by_field_name = True` works. Or should my usecase be disallowed somewhere in the library maybe.

**Comment by r7vme** [comment]
Hello, seems I also have same behavior with my snippet below

output:
```
expected <class '__main__.Eagle'>
actual <class '__main__.Duck'>
```

```python
from typing import Union
from pydantic import BaseModel


class Duck(BaseModel):
    beak: str
    wings: str


class Eagle(BaseModel):
    beak: int
    wings: int


Bird = Union[Duck, Eagle]


class Zoo(BaseModel):
    bird: Bird


awesome_eagle = Eagle(beak=1, wings=1)
zoo = Zoo(bird=awesome_eagle)

print(f"expected {type(awesome_eagle)}\nactual {type(zoo.bird)}")
```

Workaround: add fields like `type: Literal["Eagle"] = "Eagle"` to every type

**Comment by samuelcolvin** [comment]
This is a known issue, there are many duplicate issues. It will be fixed in V2.

**Comment by tmonster94** [comment]
@samuelcolvin thanks, I'll close this one for now then. Look forward to using V2
