### ISSUE TITLE
Environment variables are not loaded for nested models with uppercase variable names

### ISSUE THREAD

**Issue by 0mar** [samuelcolvin/pydantic#3936]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /private/tmp/settings/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.1 (main, Jan  6 2022, 17:54:04) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-11.6.4-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

# Bug
When nesting a model in a `Settings` class and populating it with an environment file, pydantic does not match environment variables to variables of nested models if the latter is upper cased. Example (adapted from the tutorial).

I'm thinking this is a bug because capitalization of non-nested models is handled correctly. However, if it's somehow expected behaviour, perhaps a mention in the documentation could help people out who tend to use upper case variable names for settings.

Assume the following `.env` file:
```bash
export V0=0
export V1=0
export SUB_MODEL__V2=information
```
Then the following code runs fine:

```py
from pydantic import BaseModel, BaseSettings

class SubModel(BaseModel):
    v2: str # <-- lower case


class Settings(BaseSettings):
    v0: str
    V1: str
    sub_model: SubModel

    class Config:
        env_nested_delimiter = "__"

s = Settings(_env_file='.env')
print(s.dict())
"""
{'v0': '0', 'V1': '0', 'sub_model': {'v2': 'information'}}
"""
```
but the following crashes (the only change is the capitalization of `SubModel.V2`):
```py
from pydantic import BaseModel, BaseSettings

class SubModel(BaseModel):
    V2: str # <-- upper case


class Settings(BaseSettings):
    v0: str
    V1: str
    sub_model: SubModel

    class Config:
        env_nested_delimiter = "__"

s = Settings(_env_file='.env')
print(s.dict())
"""
Traceback (most recent call last):
  File "/private/tmp/settings/pyds.py", line 15, in <module>
    s = Settings(_env_file='.env')
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
sub_model -> V2
  field required (type=value_error.missing)
"""
```
I'm guessing that https://github.com/samuelcolvin/pydantic/issues/3115 is affected by the same bug (if it is a bug), but since capitalization isn't mentioned I thought it would be best to create a new issue.

PS: Thanks for a great library 🥇

**Comment by fabigr8** [comment]
issue inherited in fastapi so +1. thx for the great work!

**Comment by Yukun4119** [comment]
> ### Checks
> * [x]  I added a descriptive title to this issue
> * [x]  I have searched (google, github) for similar issues and couldn't find anything
> * [x]  I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug
> 
> Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
> 
> ```
>              pydantic version: 1.9.0
>             pydantic compiled: True
>                  install path: /private/tmp/settings/.venv/lib/python3.10/site-packages/pydantic
>                python version: 3.10.1 (main, Jan  6 2022, 17:54:04) [Clang 13.0.0 (clang-1300.0.29.30)]
>                      platform: macOS-11.6.4-arm64-arm-64bit
>      optional deps. installed: ['dotenv', 'typing-extensions']
> ```
> 
> # Bug
> When nesting a model in a `Settings` class and populating it with an environment file, pydantic does not match environment variables to variables of nested models if the latter is upper cased. Example (adapted from the tutorial).
> 
> I'm thinking this is a bug because capitalization of non-nested models is handled correctly. However, if it's somehow expected behaviour, perhaps a mention in the documentation could help people out who tend to use upper case variable names for settings.
> 
> Assume the following `.env` file:
> 
> ```shell
> export V0=0
> export V1=0
> export SUB_MODEL__V2=information
> ```
> 
> Then the following code runs fine:
> 
> ```python
> from pydantic import BaseModel, BaseSettings
> 
> class SubModel(BaseModel):
>     v2: str # <-- lower case
> 
> 
> class Settings(BaseSettings):
>     v0: str
>     V1: str
>     sub_model: SubModel
> 
>     class Config:
>         env_nested_delimiter = "__"
> 
> s = Settings(_env_file='.env')
> print(s.dict())
> """
> {'v0': '0', 'V1': '0', 'sub_model': {'v2': 'information'}}
> """
> ```
> 
> but the following crashes (the only change is the capitalization of `SubModel.V2`):
> 
> ```python
> from pydantic import BaseModel, BaseSettings
> 
> class SubModel(BaseModel):
>     V2: str # <-- upper case
> 
> 
> class Settings(BaseSettings):
>     v0: str
>     V1: str
>     sub_model: SubModel
> 
>     class Config:
>         env_nested_delimiter = "__"
> 
> s = Settings(_env_file='.env')
> print(s.dict())
> """
> Traceback (most recent call last):
>   File "/private/tmp/settings/pyds.py", line 15, in <module>
>     s = Settings(_env_file='.env')
>   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
>   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Settings
> sub_model -> V2
>   field required (type=value_error.missing)
> """
> ```
> 
> I'm guessing that #3115 is affected by the same bug (if it is a bug), but since capitalization isn't mentioned I thought it would be best to create a new issue.
> 
> PS: Thanks for a great library 1st_place_medal

Hi, I met the similar problem this week, but in my case, even the lower_case variable name is also not working with env_nested_delimiter.
I found a solution for my case:
How to you install pydantic? 
I install it with the command `pip install pydantic[dotenv]` at first, and I met this bug.
However, when I remove it and install again with `sudo` :   `sudo pip install pydantic`, everything is good.
Hope this will help u

**Comment by aminalaee** [comment]
I think the confusion is coming from where `case_insensitive` is False by default: https://github.com/samuelcolvin/pydantic/blob/8846ec4685e749b93907081450f592060eeb99b1/pydantic/env_settings.py#L79-L88

This causes the following to lower-case all env variables by default:
https://github.com/samuelcolvin/pydantic/blob/8846ec4685e749b93907081450f592060eeb99b1/pydantic/env_settings.py#L160-L163

This works ok:

```python
import os

from pydantic import BaseModel, BaseSettings

os.environ.setdefault("v0", "A")
os.environ.setdefault("V1", "B")
os.environ.setdefault("sub_model__V2", "C")

class SubModel(BaseModel):
    V2: str


class Settings(BaseSettings):
    v0: str
    V1: str
    sub_model: SubModel

    class Config:
        case_sensitive = True
        env_nested_delimiter = "__"

print(Settings().dict())
# {'v0': 'A', 'V1': 'B', 'sub_model': {'V2': 'C'}}
```

@samuelcolvin Maybe at this time it doesn't make sense to flip this behaviour, is it worth adding docs and examples? I'll be happy to do that.

**Comment by samuelcolvin** [comment]
Agreed, let's update the docs now and remember to change the behavior to default to case insensitive in v2.
