### ISSUE TITLE
Nested fields not json parsed when they are complex

### ISSUE THREAD

**Issue by irsath** [samuelcolvin/pydantic#3971]
### Checks

* [ ] I added a descriptive title to this issue
* [ ] I have searched (google, github) for similar issues and couldn't find anything
* [ ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/irsath/workspace/pydantic_bug/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Dec 12 2021, 10:56:00)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.2.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

Given the code below

```py
from typing import Set

from pydantic import (
    BaseModel,
    BaseSettings
)

class SubConfig(BaseModel):
    subset: Set[str]

class Settings(BaseSettings):
    topset: Set[str]
    sub: SubConfig

    class Config:
        env_nested_delimiter = "__"
        env_file = ".env"
        env_file_encoding = "utf-8"


print(Settings().dict())
```

Given the `.env` file below
```env

topset='["foo.com"]'
sub__subset='["bar.com"]'
```

According to the [documentation](https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values)
> Complex types like list, set, dict, and sub-models are populated from the environment by treating the environment variable's value as a JSON-encoded string.

We expect as an output:
```py
{'topset': {'foo.com'}, 'sub': {'subset': {'bar.com'}}}
```

Actual ouput:
````
Traceback (most recent call last):
  File "....../main.py", line 21, in <module>
    print(Settings().dict())
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
sub -> subset
  value is not a valid set (type=type_error.set)
````

# Possible root cause

It seems that while root level fields are JSON parsed when they are complex, nothing is done for nested fields loaded using env delimiters.
[env_settings.py#188](https://github.com/samuelcolvin/pydantic/blob/7f90b2f342ba338957bb8dfff3ead760edcdd9bf/pydantic/env_settings.py#L188) 
```py
 # field is complex but no value found so far, try explode_env_vars
env_val_built = self.explode_env_vars(field, env_vars)
    if env_val_built:
    d[field.alias] = env_val_built        ===> No complexity checks on subfields
```

**Comment by samuelcolvin** [comment]
is this new in v1.9?
