### ISSUE TITLE
Nested Generic Models under PEP604 convention break Pydantic

### ISSUE THREAD

**Issue by charles-vdulac** [samuelcolvin/pydantic#4048]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

First of all, thanks for the outstanding job with Pydantic!

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /usr/local/opt/pyenv/versions/3.10.3/envs/spark-prices-3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.3 (main, May  4 2022, 17:20:41) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

According to the documentation, we can create nested Generic Models: 

```py
T = TypeVar("T")

class InnerT(GenericModel, Generic[T]):
    inner: Optional[T]


class OuterT(GenericModel, Generic[T]):
    outer: T
    nested: Optional[InnerT[T]]


nested = InnerT[int](inner=1)
print(OuterT[int](outer=1, nested=nested))
```

That's working very well!

But, now, in Python 3.10, thanks to the PEP 604, `Optional[]` can be replaced by the `| None` operator. And that breaks Pydantic:

```py
T = TypeVar("T")


class Pep604InnerT(GenericModel, Generic[T]):
    inner: T | None


class Pep604OuterT(GenericModel, Generic[T]):
    outer: T
    nested: Pep604InnerT[T] | None


nested = Pep604InnerT[int](inner=1)
print(Pep604OuterT[int](outer=1, nested=nested))
```

Traceback:

```
Traceback (most recent call last):
  File "pydantic_bug.py", line 55, in <module>
    print(Pep604OuterT[int](outer=1, nested=nested))
  File ".../python3.10/site-packages/pydantic/generics.py", line 136, in __class_getitem__
    _prepare_model_fields(created_model, fields, instance_type_hints, typevars_map)
  File ".../python3.10/site-packages/pydantic/generics.py", line 359, in _prepare_model_fields
    concrete_type = replace_types(field_type_hint, typevars_map)
  File ".../python3.10/site-packages/pydantic/generics.py", line 263, in replace_types
    return origin_type[resolved_type_args]
TypeError: 'type' object is not subscriptable
```

**Comment by samuelcolvin** [comment]
Does the `Outer` model need to be generic to cause this? Shouldn't be too hard to fix.

**Comment by charles-vdulac** [comment]
Yes. This piece of code is working well:

```python
from typing import Generic
from typing import TypeVar

from pydantic.generics import GenericModel, BaseModel


T = TypeVar("T")


class Inner(GenericModel, Generic[T]):
    inner: T | None


class Outer(BaseModel):
    outer: int
    nested: Inner | None


nested = Inner[int](inner=1)

print(Outer(outer=1, nested=nested))

```

**Comment by Viicos** [comment]
This seems to work now on latest (2.5.0)
