### ISSUE TITLE
json_encoders not being used on list members

### ISSUE THREAD

**Issue by cfxegbert** [samuelcolvin/pydantic#4085]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/minskr/Library/Caches/pypoetry/virtualenvs/mei-imf-z9_q_NMv-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Apr 26 2022, 19:43:24) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-11.6.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from typing import Any, Callable, Generator, List
from pydantic import BaseModel, errors


class HexBytes(bytes):
    @classmethod
    def __get_validators__(cls) -> Generator[Callable[..., Any], None, None]:
        yield cls.__validate

    @classmethod
    def __validate(cls, val: Any) -> "HexBytes":
        if isinstance(val, bytes):
            return cls(val)
        if isinstance(val, bytearray):
            return cls(val)
        if isinstance(val, str):
            return cls.fromhex(val)
        raise errors.BytesError()


class WithHex(BaseModel):
    hexBytes: HexBytes

    class Config:
        json_encoders = {
            bytes: lambda bs: bs.hex(),
            HexBytes: lambda bs: bs.hex()
        }


class WithList(BaseModel):
    listOfHexBytes: List[WithHex]


with_hex_1 = WithHex(hexBytes=b'\x80')
with_hex_2 = WithHex(hexBytes=b'\x81')

with_list = WithList(listOfHexBytes=[with_hex_1, with_hex_2])
```
Calling json() on the leaf class works fine
```py
with_hex_1.json()
'{"hexBytes": "80"}'
```
Calling json() on the individual list item works fine
```py
with_list.listOfHexBytes[0].json()
'{"hexBytes": "80"}'
```
Calling json() on the model containing the list will fail
```
with_list.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 490, in pydantic.main.BaseModel.json
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 95, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 52, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
Using a custom BaseModel works
```py
from typing import Any, Callable, Generator, List, Optional
from pydantic import BaseModel, errors


class HexBytes(bytes):
    @classmethod
    def __get_validators__(cls) -> Generator[Callable[..., Any], None, None]:
        yield cls.__validate

    @classmethod
    def __validate(cls, val: Any) -> "HexBytes":
        if isinstance(val, bytes):
            return cls(val)
        if isinstance(val, bytearray):
            return cls(val)
        if isinstance(val, str):
            return cls.fromhex(val)
        raise errors.BytesError()


class MyBaseModel(BaseModel):
    class Config:
        json_encoders = {
            bytes: lambda bs: bs.hex(),
            HexBytes: lambda bs: bs.hex()
        }


class WithHex(MyBaseModel):
    hexBytes: HexBytes


class WithList(MyBaseModel):
    listOfHexBytes: List[WithHex]


with_hex_1 = WithHex(hexBytes=b'\x80')
with_hex_2 = WithHex(hexBytes=b'\x81')

with_list = WithList(listOfHexBytes=[with_hex_1, with_hex_2])
```
```py
with_list.json()
'{"listOfHexBytes": [{"hexBytes": "80"}, {"hexBytes": "81"}]}'
```

**Comment by samuelcolvin** [comment]
Currently `json_encoders` on child models is not used when converting to JSON.

I think we could improve this, but it's not a bug, it's just a limitation.

**Comment by cfxegbert** [comment]
Can this limitation be added to the documentation at least?  Is there any way to change this over to a feature request?

**Comment by samuelcolvin** [comment]
I have plans to significantly alter for export, including JSON work in V2. That should fix this.

If you want to add a pr for the docs now, feel free. Should go live before we move to V2.
