### ISSUE TITLE
'IndexError: tuple index out of range' when using a generic class that extends dict

### ISSUE THREAD

**Issue by joaompfe** [samuelcolvin/pydantic#4100]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/joaompfe/.cache/pypoetry/virtualenvs/XXX/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
                     platform: Linux-5.17.8-arch1-1-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
```

Sample:
```py
from typing import Generic, TypeVar

from pydantic import BaseModel, ValidationError
from pydantic.fields import ModelField


if __name__ == '__main__':
    T = TypeVar("T")

    class Inference(dict, Generic[T]):

        value: T
        conf: float

        def __init__(self, value, conf):
            self.value = value
            self.conf = conf
            super().__init__({
                "value": self.value,
                "conf": self.conf
            })

        @classmethod
        def __get_validators__(cls):
            yield cls.validate

        @classmethod
        def validate(cls, v, field: ModelField):
            # https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types
            if not isinstance(v, cls):
                raise TypeError(f"Type should be {cls} but is {type(v)}.")
            if not field.sub_fields:
                return v
            value_type = field.sub_fields[0]
            valid_value, error = value_type.validate(v.value, {}, loc="value")
            if error:
                raise ValidationError(error, cls)
            return v


    # Just testing the class
    inference = Inference(True, 0.99)
    inference["conf"] = 0.98
    print(inference)

    # Here is the problem
    class ModelRun(BaseModel):
        result: Inference[bool]
```

Output:
```
{'value': True, 'conf': 0.98}
Traceback (most recent call last):
  File "/home/joaompfe/XXX.py", line 45, in <module>
    class ModelRun(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 710, in pydantic.fields.ModelField._type_analysis
IndexError: tuple index out of range

Process finished with exit code 1

```

**Comment by samuelcolvin** [comment]
Ye, we don't support this. Something similar should be possible in pydantic V2 when that's released by using a TypedDict.
