### ISSUE TITLE
Problems with constrained strings

### ISSUE THREAD

**Issue by ptrxyz** [samuelcolvin/pydantic#4248]
### Checks

# Bug

The code provided below results in several errors:
```
python pydantictest.py
Traceback (most recent call last):
  File "/home/ptrxyz/scratch/pydantictest.py", line 21, in <module>
    ms = MyStuff(dept=MYLITERAL, dept2=MYLITERAL, dept3=MYLITERAL)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for MyStuff
dept
  ensure this value has at most 6 characters (type=value_error.any_str.max_length; limit_value=6)
dept2
  ensure this value has at most 6 characters (type=value_error.any_str.max_length; limit_value=6)
```

1.  all three should do the same: enforce a length of 6 characters and strip whitespaces. However the results are different, since the last paramter (dept3) does not trigger a validation error.
2. I don't know if it's by design, but I would assume that any mutations, like `strip_whitespace`, would be applied before any checks, like the length checks here. If so, then the first two should not trigger a validation error, if not, then the last one should. Either way it's inconsistent and one of them is probably wrong.
3. Pylance validation fails with the third parameter, resulting in a `GeneralTypeIssue`: 
![image](https://user-images.githubusercontent.com/209056/179539699-1e49768a-3069-44da-9437-51e603ff41d7.png)
Is there any workarounds/fixed for that, besides turning off pylance?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/ptrxyz/.cache/pypoetry/virtualenvs/dfnt-account-service-Prn8tZhj-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
                     platform: Linux-5.18.12-zen1-1-zen-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

```py
from typing import Annotated
from pydantic import BaseModel, Field, ConstrainedStr


MinMaxString = Annotated[str, Field(min_length=6, max_length=6, strip_whitespace=True)]


class CSTR(ConstrainedStr):
    min_length: int = 6
    max_length: int = 6
    strip_whitespace: bool = True


class MyStuff(BaseModel):
    dept: str = Field(..., min_length=6, max_length=6, strip_whitespace=True)
    dept2: MinMaxString
    dept3: CSTR


MYLITERAL = "123456 "
ms = MyStuff(dept=MYLITERAL, dept2=MYLITERAL, dept3=MYLITERAL)
```

**Comment by samuelcolvin** [comment]
This is not a bug, it's a question, we have the discussion forum for questions.

Also, if you are creating a bug, please have the courtesy to fill in the template properly.

No, there's no way to get pylance to understand `dept3` AFAIK, but perhaps you should try asking the pylance team?

**Comment by ptrxyz** [comment]
Oh, sorry for that, I tried to stick to the template, I added the checklist in the beginning again.

However, my bug report is about the inconsistency about how `strip_whitspace` and length checks are handled, the points about Pylance are indeed simply questions I thought that might be helpful.

**Comment by samuelcolvin** [comment]
Ye, the checks are done in a different order I'm afraid.

This will be fixed in V2, i doubt it's worth fixing before then, the plan i to get to V2 as soon as possible.

**Comment by ptrxyz** [comment]
Ok, thanks! For anyone passing by in the meanwhile, I got this as a workaround until then:
(pylance, mypy are happy, as well as stripping the whitepsaces and length checks are in order and json_schema are working)

```py
class CSTR(ConstrainedStr):
    min_length: int = 6
    max_length: int = 6
    strip_whitespace: bool = True


class MyStuff(BaseModel):
    test: CSTR | str = Field(..., min_length=6, max_length=6, strip_whitespace=True)

ms = MyStuff(test="123456")         # works, ms.test="123456"
ms = MyStuff(test=" 123456   ")     # works, ms.test="123456", whitespaces stripped before length check
ms = MyStuff(test="12345")          # fails, Exception indicates that ms.test is too short
ms = MyStuff(test="1234567")        # fails, Exception indicates that ms.test is too long
ms.schema_json()                    # works, however ms.test is defined as anyOf of two identical types
```
