### ISSUE TITLE
SecretStr is not JSON serializable

### ISSUE THREAD

**Issue by nymous** [samuelcolvin/pydantic#462]
# Bug / Feature request (not sure?)

* OS: **Archlinux 5.0.5-arch1-1-ARCH SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019 x86_64 GNU/Linux**
* Python version `import sys; print(sys.version)`: **3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.23**

```py
from pydantic import BaseModel, SecretStr


class User(BaseModel):
    username: str
    password: SecretStr


user = User(username='nymous', password='my-password')
print(user)
print(user.dict())
print(user.json())
```

**Expected result:**
I don't really know, maybe a JSON with a '****' field, or the field excluded.

**Actual result:**

<details>
<summary>Console output</summary>

```
User username='nymous' password=SecretStr('**********')
{'username': 'nymous', 'password': SecretStr('**********')}
Traceback (most recent call last):
  File "/tmp/tmp.ZRa0tsEfhw/.venv/lib/python3.7/site-packages/pydantic/json.py", line 45, in pydantic_encoder
    encoder = ENCODERS_BY_TYPE[type(obj)]
KeyError: <class 'pydantic.types.SecretStr'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    print(user.json())
  File "/tmp/tmp.ZRa0tsEfhw/.venv/lib/python3.7/site-packages/pydantic/main.py", line 312, in json
    **dumps_kwargs,
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/tmp.ZRa0tsEfhw/.venv/lib/python3.7/site-packages/pydantic/json.py", line 47, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'SecretStr' is not JSON serializable
```

</details>

**Comment by samuelcolvin** [comment]
I agree it shouldn't cause an error.

I would say the best option would be to use the result of `str(secret_str)`?

@Atheuz you did all the work, what's your feeling?

**Comment by tiangolo** [comment]
I would suggest, by default, a JSON with `***`, but add another parameter to `.dict(show_secrets=False)` and `.json(show_secrets=False)` or something similar.

To make it possible to extract the whole model as `dict` / JSON, for example to store it in a NoSQL.

**Comment by samuelcolvin** [comment]
I don't really want to add more arguments to `dict()` and `json()`, but we can add an example of a custom encoder that serialises secrets.

**Comment by Atheuz** [comment]
@samuelcolvin @nymous 

It appears that this is a general issue:

```
import pydantic
import os

class Settings(pydantic.BaseModel):
    fp: pydantic.FilePath
    
def main():
    conf = Settings(fp="testfile.txt")
    print(conf.json())
    
if __name__ == '__main__':
    main()

Traceback (most recent call last):
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/json.py", line 45, in pydantic_encoder
    encoder = ENCODERS_BY_TYPE[type(obj)]
KeyError: <class 'pathlib.PosixPath'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-pydantic2.py", line 12, in <module>
    main()
  File "test-pydantic2.py", line 9, in main
    print(conf.json())
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/main.py", line 312, in json
    **dumps_kwargs,
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/json.py", line 47, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'PosixPath' is not JSON serializable
```
OR

```
import pydantic
import os

class Settings(pydantic.BaseModel):
    email: pydantic.NameEmail
    
def main():
    conf = Settings(email="lasse gravesen    <gravesenlasse@gmail.com>")
    print(conf.json())
    
if __name__ == '__main__':
    main()

Traceback (most recent call last):
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/json.py", line 45, in pydantic_encoder
    encoder = ENCODERS_BY_TYPE[type(obj)]
KeyError: <class 'pydantic.types.NameEmail'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-pydantic2.py", line 12, in <module>
    main()
  File "test-pydantic2.py", line 9, in main
    print(conf.json())
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/main.py", line 312, in json
    **dumps_kwargs,
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/atheuz/.local/share/virtualenvs/sandbox36/lib/python3.6/site-packages/pydantic/json.py", line 47, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'NameEmail' is not JSON serializable
```

This can be fixed by adding types to the dict lookup table in `json.py`, i.e. like this:
```
ENCODERS_BY_TYPE: Dict[Type[Any], Callable[[Any], Any]] = {
    IPv4Address: str,
    IPv6Address: str,
    IPv4Interface: str,
    IPv6Interface: str,
    IPv4Network: str,
    IPv6Network: str,
    SecretStr: str,
    UUID: str,
    datetime.datetime: isoformat,
    datetime.date: isoformat,
    datetime.time: isoformat,
    datetime.timedelta: lambda td: td.total_seconds(),
    set: list,
    frozenset: list,
    GeneratorType: list,
    bytes: lambda o: o.decode(),
    Decimal: float,
}
```

Then it's encoded as a str and would be outputted like this:

```
test.json()
'{"secret": "SecretStr(\'**********\')"}'
```

**Comment by Atheuz** [comment]
Note my PR here: https://github.com/samuelcolvin/pydantic/pull/465
