### ISSUE TITLE
`.dict(by_alias=True)` throws an exception when trying to call with extra keys

### ISSUE THREAD

**Issue by JaewonKim** [samuelcolvin/pydantic#488]
# Bug

* OS: Mac OS
* Python version: 
```
3.7.2 (default, Mar 19 2019, 17:39:18) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```
* Pydantic version: 0.23

I'm trying to use extra columns for my model. And I expected `.dict(by_alias=True)` to return dict for my model with alias, but I received an exception. I think this is because `get_key` is using `self.fields` that doesn't include extra keys.
```py
from pydantic import Schema, Extra, BaseModel, BaseConfig


class ModelTest(BaseModel):
    a: str = Schema(None, alias='b')

    class Config(BaseConfig):
        extra = Extra.allow


if __name__ == '__main__':
        m = ModelTest(extra_column='extra')
        print(m.extra_column)  # extra
        print(m.dict())  # {'a': None, 'extra_column': 'extra'}
        print(m.dict(by_alias=True))  # error
```

```
Traceback (most recent call last):
  File "...", line 41, in ...
    print(m.dict(by_alias=True))  # error
  File ".../python3.7/site-packages/pydantic/main.py", line 282, in dict
    get_key(k): v for k, v in self._iter(by_alias=by_alias, skip_defaults=skip_defaults)
  File ".../python3.7/site-packages/pydantic/main.py", line 282, in <dictcomp>
    get_key(k): v for k, v in self._iter(by_alias=by_alias, skip_defaults=skip_defaults)
  File ".../python3.7/site-packages/pydantic/main.py", line 293, in <lambda>
    return lambda fields, key: fields[key].alias
KeyError: 'extra_column'
```

**Comment by samuelcolvin** [comment]
thanks for reporting, fix shouldn't be too hard. PR welcome or I'll fix in a week or so.
