### ISSUE TITLE
Schema generation fails for tuple with ellipsis

### ISSUE THREAD

**Issue by haizaar** [samuelcolvin/pydantic#600]
# Bug
Good day,
Thanks again for this awesome lib!

The issue: pydantic can't generate JSON schema for fields defined as Tuple with ellipsis. Consider the following:
```python
from typing import Tuple
from pydantic import BaseModel

class Foo(BaseModel):
    names: Tuple[str, ...]

print(Foo.schema())
```
which breaks with:
```
Traceback (most recent call last):
  File "/tmp/model.py", line 10, in <module>
    print(Foo.schema())
  File "pydantic/main.py", line 431, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 225, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 536, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 563, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 279, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 502, in pydantic.schema.field_type_schema
AssertionError: Shape.TUPLE_ELLIPS
```

For bugs/questions:
* OS: Ubuntu 16.04, amd64
* Python version 3.7.3
* Pydantic version 0.28

**Comment by tiangolo** [comment]
Thanks, I'll check it as soon as I get a chance.

**Comment by tiangolo** [comment]
This was fixed some time ago, I don't remember in which exact version.

But in the latest (currently `v1.5.1`) it works as expected, the output is:

```
{'title': 'Foo', 'type': 'object', 'properties': {'names': {'title': 'Names', 'type': 'array', 'items': {'type': 'string'}}}, 'required': ['names']}
```
