### ISSUE TITLE
Better error message for Enums

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/pydantic#671]
# Feature Request

better error message for Enums would be interesting, so far when i have
```
class AvailableLang(str, Enum):
    en = "en"
    fr = "fr"
    de = "de"


class AvailableTheme(str, Enum):
    dark = "dark"
    light = "light"


class UserSettings(BaseModel):
    lang: AvailableLang
    theme: AvailableTheme
    avatar: UrlStr

    class Config:
        use_enum_values = True
```

and that i pass let's say "gb" to my lang, I got the following:

```
{
  "detail": [
    {
      "loc": [
        "body",
        "user_setting",
        "lang"
      ],
      "msg": "value is not a valid enumeration member",
      "type": "type_error.enum"
    }
  ]
}
````

a msg like value is not a valid enumeration member, acceptable values are en,fr,de would be super useful

oups that's FasAPI rendering the error, with pydantic it's
`value is not a valid enumeration member (type=type_error.enum)`
that could maybe be improved by writing
`value is not a valid enumeration member, acceptable values are en,fr,de (type=type_error.enum)`
```
UserSettings(
        lang='gb', theme=AvailableTheme.dark, avatar="https://avatarurl.com/avatar.png"
    )
backend-tests_1  | Traceback (most recent call last):
backend-tests_1  |   File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
backend-tests_1  |     exec(code_obj, self.user_global_ns, self.user_ns)
backend-tests_1  |   File "<ipython-input-5-e51f15740c90>", line 2, in <module>
backend-tests_1  |     lang='gb', theme=AvailableTheme.dark, avatar="https://avatarurl.com/avatar.png"
backend-tests_1  |   File "/usr/local/lib/python3.7/site-packages/pydantic/main.py", line 270, in __init__
backend-tests_1  |     values, fields_set, _ = validate_model(self, data)
backend-tests_1  |   File "/usr/local/lib/python3.7/site-packages/pydantic/main.py", line 697, in validate_model
backend-tests_1  |     raise ValidationError(errors)
backend-tests_1  | pydantic.error_wrappers.ValidationError: 1 validation error
backend-tests_1  | lang
backend-tests_1  |   value is not a valid enumeration member (type=type_error.enum)
```

**Comment by dmontagu** [comment]
I put a proposed implementation in #673

**Comment by samuelcolvin** [comment]
I think this is fixed in v1.
