### ISSUE TITLE
[Bug] Regression in ValidationError serializarion with Enums

### ISSUE THREAD

**Issue by jcugat** [samuelcolvin/pydantic#696]
# Bug

For bugs/questions:
* OS: macOS Mojave 10.14.5 (18F132)
* Python version `import sys; print(sys.version)`: 3.6.8
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.31

This is a minimal snippet to reproduce it:

```py
from enum import Enum
from pydantic import BaseModel, Extra, ValidationError

class MyEnum(str, Enum):
    VALID = "VALID"

class Foo(BaseModel):
    bar: MyEnum

try:
    Foo(bar="INVALID")
except ValidationError as e:
    print(e.json())
```

And the stacktrace:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/josepcugat/.pyenv/versions/current/lib/python3.6/site-packages/pydantic/main.py", line 276, in __init__
    values, fields_set, _ = validate_model(__pydantic_self__, data)
  File "/Users/josepcugat/.pyenv/versions/current/lib/python3.6/site-packages/pydantic/main.py", line 790, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
bar
  value is not a valid enumeration member; permitted: 'VALID' (type=type_error.enum; enum_type=<enum 'MyEnum'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/josepcugat/.pyenv/versions/current/lib/python3.6/site-packages/pydantic/error_wrappers.py", line 62, in json
    return json.dumps(self.errors(), indent=indent)
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Users/josepcugat/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'EnumMeta' is not JSON serializable
```

Using pydantic 0.30.1 works as expected:

```
>>> from enum import Enum
>>> from pydantic import BaseModel, Extra, ValidationError
>>>
>>> class MyEnum(str, Enum):
...     VALID = "VALID"
...
>>> class Foo(BaseModel):
...     bar: MyEnum
...
>>> try:
...     Foo(bar="INVALID")
... except ValidationError as e:
...     print(e.json())
...
[
  {
    "loc": [
      "bar"
    ],
    "msg": "value is not a valid enumeration member",
    "type": "type_error.enum"
  }
]
```

I suspect it has something to do with https://github.com/samuelcolvin/pydantic/pull/673 since now we are trying to serialize the `ctx` property of the error.

**Comment by samuelcolvin** [comment]
thanks for reporting, should be pretty simple to fix. PR welcome.

**Comment by hound672** [comment]
Maybe just remove 'ctx'? 
In error_wrapper.py 

  ```
def json(self, *, indent: Union[None, int, str] = 2) -> str:
        errors = self.errors()
        for error in errors:
            if 'ctx' in error:
                del error['ctx']
        return json.dumps(errors, indent=indent)
```

**Comment by samuelcolvin** [comment]
Unfortunately that may break many users existing implementations.

**Comment by hound672** [comment]
But 0.30.1  does not return 'ctx' in json.

**Comment by dmontagu** [comment]
@hound672 'ctx' is returned for other error `ValidationError` instances (just not those arising due to `EnumError`). I created a PR that fixes this by just putting the list of values in the context, rather than the enum type.

**Comment by samuelcolvin** [comment]
thanks for reporting.
