### ISSUE TITLE
[QUESTION: How can I use models with relationships?

### ISSUE THREAD

**Issue by deterok** [samuelcolvin/pydantic#709]
When I try to use a model with relationship, an error occurs: 
```
Traceback (most recent call last):
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 37, in __call__
    await self.app(scope, receive, send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 122, in __call__
    raise exc from None
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/mrd/Projects/itg/orion/feature_vstack/middelware.py", line 10, in LoggerMiddleware
    response = await next_call(request)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/starlette/routing.py", line 40, in app
    response = await func(request)
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/fastapi/routing.py", line 122, in app
    skip_defaults=response_model_skip_defaults,
  File "/home/mrd/Projects/itg/orion/.env/lib/python3.7/site-packages/fastapi/routing.py", line 54, in serialize_response
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
response -> interfaces -> 0
  value is not a valid dict (type=type_error.dict)
```
`interfaces` is simple relationship field.

**Comment by samuelcolvin** [comment]
Need more details.

**Comment by dmontagu** [comment]
I saw a very similar looking issue on FastAPI yesterday; try adding
```
class Model(BaseModel):
    ...
    # add this:
    class Config:
        orm_mode = True
```
to whatever model your endpoint is returning a list of. (I'm not exactly sure why this works, but I think it has to do with FastAPI internals.)

**Comment by samuelcolvin** [comment]
closing this as not enough detail and no response.
