### ISSUE TITLE
Cannot add extra fields when `validate_assignment` is True

### ISSUE THREAD

**Issue by YaraslauZhylko** [samuelcolvin/pydantic#723]
# Bug

* OS: **Ubuntu Linux 18.04.2 LTS**
* Python version: **3.6.7**
* Pydantic version: **0.32**

When `validate_assignment` option is on, adding an extra field to existing pydantic object causes `KeyError`:

```py
import contextlib
import datetime
import pydantic


class ModelWithoutValidation(pydantic.BaseModel):
    name: str = None
    birthdate: datetime.date = None

    class Config:
        extra = pydantic.Extra.allow
        validate_assignment = False  # <<< !!!


obj = ModelWithoutValidation(name="Jim Smith")
obj.name = "John Doe"  # OK: Does not fail because assignment is not validated
obj.birthdate = "1983-16-72"  # OK: Does not fail because assignment is not validated
obj.fake_stuff = "asdf"  # OK: Can assign new field


class ModelWithValidation(pydantic.BaseModel):
    name: str = None
    birthdate: datetime.date = None

    class Config:
        extra = pydantic.Extra.allow
        validate_assignment = True  # <<< !!!


obj = ModelWithValidation(name="Jim Smith")
obj.name = "John Doe"  # OK: Does not fail because the value is acceptable
with contextlib.suppress(pydantic.ValidationError):
    obj.birthdate = "1983-16-72"  # OK: Fails because the value is wrong
obj.fake_stuff = "asdf"
# FAIL: Cannot assign new field becaue there's no valiator
# Traceback (most recent call last):
#   File "/home/yaraslau/Projects/Dialogue/tmp/test.py", line 34, in <module>
#     obj.fake_stuff = "asdf"
#   File "pydantic/main.py", line 294, in pydantic.main.BaseModel.__setattr__
# KeyError: 'fake_stuff'
```

The problem is actually here: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L286

As far as I understand the failure is caused by `__setattr__` trying to get the validator(s) for a non-existent field.

**I guess, it should just ignore any validation for extra fields if they are not explicitly defined within the model.**

_P.S.: Here's the PR: https://github.com/samuelcolvin/pydantic/pull/724_

_P.P.S.: I guess this may be considered **"a bug in v0.32"**._

**Comment by YaraslauZhylko** [comment]
Mildly related to https://github.com/samuelcolvin/pydantic/issues/515
