### ISSUE TITLE
duplicated errors when validators raise ValidationError

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#737]
# Bug

As a work around for #619 I tried the following

```py
from pydantic import VERSION, BaseModel, Union, validator
from typing_extensions import Literal
print('pydantic version:', VERSION)

class Foo(BaseModel):
    model_type: Literal['foo']
    f: int

class Bar(BaseModel):
    model_type: Literal['bar']
    b: int

class MyModel(BaseModel):
    foobar: Union[Foo, Bar]

    @validator('foobar', pre=True)
    def check_action(cls, v):
        if isinstance(v, dict):
            model_type = v.get('model_type')
            if model_type == 'foo':
                return Foo(**v)
            if model_type == 'var':
                return Bar(**v)
        return v

MyModel(foobar={'model_type': 'foo', 'f': 'x'})
```
Output:
```
pydantic version: 0.32.1
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    MyModel(foobar={'model_type': 'foo', 'f': 'x'})
  File "pydantic/main.py", line 275, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 785, in pydantic.main.validate_model
pydantic.error_wrappers.ValidationError: 2 validation errors for MyModel
foobar -> f
  value is not a valid integer (type=type_error.integer)
foobar -> f
  value is not a valid integer (type=type_error.integer)
```

When validators raise `ValidationError` the errors are duplicated.

Won't be that common, but should be fixed.

**Comment by samuelcolvin** [comment]
I was being dumb, just that I didn't have `whole=True`, I've added a test to demonstrate this.
