### ISSUE TITLE
Type Validation with Dataclasses and Marshmallow

### ISSUE THREAD

**Issue by philip-zelichenko** [samuelcolvin/pydantic#797]
* OS: Mac
* Python version 3.6.7
* Pydantic version 0.32.2

```
from dataclasses import field
from typing import List, Optional

import marshmallow.validate
# from marshmallow_dataclass import dataclass
from pydantic.dataclasses import dataclass

@dataclass
class FilesConfigObject:
    type: str = field(metadata={'validate': marshmallow.validate.OneOf(('person', 'company', 'time_based')),
                                'required': True})
    gcp_bucket: str = field(metadata={'validate': marshmallow.validate.OneOf(('leadspace_dev_cust_data',
                                                                              'leadspace_cust_data')),
                                      'required': True})
    gcp_path: str
    columns_standardization: ColumnsObject = field(metadata={'required': True})
    aggregation_config: Optional[AggregationConfigObject] = field(metadata={'required': False})
    goal_config: Optional[GoalConfigObject] = field(metadata={'required': False})
```

Hi All, following consideration of moving to pydantic, I've encountered a few issues related to my current usage of dataclasses and compitability with pydantic.

1. I seems like the `field(metadata={'required': False})` usage in defining the data class isn't being taking into consideration. If nit providing a goal_config, a ValidationEror is raised
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: __init__() missing 3 required positional arguments: 'active', 'goal', and 'predictive_model'
```

2. OneOf example also not being validated by pydantic

3. Boolean validation for the following
```@dataclass
class ModeConfigObject:
    active: bool = field(metadata={'required': True})
    goal: bool = field(metadata={'required': True})```

is accepted
```ModeConfigObject('fdafasf', 'a', 'a')
...
ModeConfigObject(active=False, goal=False, predictive_model=False)```

**Comment by samuelcolvin** [comment]
pydantic makes not claim to support `dataclasses.field`, especially `metadata` which has no strict meaning anyway.

You should use a default value if you want a field to not be required as per the docs.

You should use `@validator`s for OneOf validation and similar.

Boolean logic will change in v1, see #617. If you want very strict boolean logic you can use `StrictBool` now.

hope that helps.

**Comment by philip-zelichenko** [comment]
```@dataclass
class FilesConfigObject:
    type: str
    gcp_bucket: str
    gcp_path: str
    columns_standardization: Optional[ColumnsObject] = None
    aggregation_config: Optional[AggregationConfigObject] = None
    goal_config: Optional[GoalConfigObject] = None

    @validator('type', pre=True)
    def file_type_validator(cls, file_type):
        if file_type not in ('person', 'company', 'time_based'):
            raise ValidationError('File Type must be one of: person, company or time_based')
        return file_type

    @validator('gcp_bucket', pre=True)
    def gcp_bucket_validator(cls, gcp_bucket):
        if gcp_bucket not in ('leadspace_dev_cust_data', 'leadspace_cust_data'):
            raise ValidationError('GCP Bucket must be one of: leadspace_dev_cust_data or leadspace_cust_data')
        return gcp_bucket
```

@samuelcolvin it seems that when defining the follwoing validators I get the following error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 8, in __init__
  File "/Users/philip/dev/leadspace/python/icp-analytics/venv/lib/python3.6/site-packages/pydantic/dataclasses.py", line 75, in _pydantic_post_init
    d = validate_model(self.__pydantic_model__, self.__dict__, cls=self.__class__)[0]
  File "/Users/philip/dev/leadspace/python/icp-analytics/venv/lib/python3.6/site-packages/pydantic/main.py", line 785, in validate_model
    raise err
pydantic.error_wrappers.ValidationError: 2 validation errors for FilesConfigObject
type
  __init__() missing 1 required positional argument: 'model' (type=type_error)
gcp_bucket
  __init__() missing 1 required positional argument: 'model' (type=type_error)
```

**Comment by samuelcolvin** [comment]
I think this is just that you're using `ValidationError` which is not suitable in this scenario. Use `ValueError` instead.
