### ISSUE TITLE
Cannot add dynamically built validators

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#806]
I guess my use-case is somewhat esoteric, but I found myself writing a bunch of validators for different BaseModels that all almost look the same and wanted to refactor some code to share code of the validators, but then ran into a "duplicate validator function". I understand this was added to help users not to accidentally overwrite another validator, but unfortunately this check seems to prevent what I want to do => minimal code example below:

```python
from pydantic import validator, BaseModel

def build_validate_func(name: str):
    def validate_func(cls, v, values):
        if v != name:
            raise ValueError()
        return v
    return validate_func

class Foo(BaseModel):
    name: str
    
    validator("name")(build_validate_func("bar"))
    
class Bar(BaseModel):
    name: str
    
    validator("name")(build_validate_func("foo"))
    
Traceback (most recent call last):
  File "/Users/timon/.pyenv/versions/3.7.3/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<input>", line 4, in Bar
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/lumi-py3.7/lib/python3.7/site-packages/pydantic/class_validators.py", line 56, in dec
    raise ConfigError(f'duplicate validator function "{ref}"')
pydantic.errors.ConfigError: duplicate validator function "__main__.build_validate_func.<locals>.validate_func"
```

I think my issue would be resolved if the check for duplicate validator functions would not be for all different BaseModels defined in a module, but just per BaseModel.

Thanks for reading this :)
Timon

**Comment by timonbimon** [comment]
> Sounds good, the other solution would be to manually change the name of the function returned by `build_validate_func` to something like
> 
> ```python
> validate_func.__qualname__ = 'validate_func' + name
> return validate_func
> ```

Ah thanks, I was playing around with __name__ and that wasn't working. __qualname__ does the trick.

**Comment by adriangb** [comment]
Have any changes broken this approach? I tried the following today and it is not working as expected:
```python3
from pydantic import validator, BaseModel

def build_validate_func(name: str):
    def validate_func(cls, v):
        if v != name:
            raise ValueError()
        return v
    validate_func.__qualname__ = 'validate_func' + name
    return validate_func

class Foo(BaseModel):
    name: str
    
    validator("name")(build_validate_func("foo"))  # name must be foo

class Bar(BaseModel):
    name: str
    
    @validator("name")
    def validate_func(cls, v):
        name = "bar"  # name must be bar
        if v != name:
            raise ValueError()
        return v

Foo(name="foo")  # passes as expected
Foo(name="notfoo")  # passes but should fail

Bar(name="bar")   # passes as expected
Bar(name="notbar")   # fails as expected
```

**Comment by adriangb** [comment]
The answer was trivial:
```python3
class Foo(BaseModel):
    name: str
    
    validate_foo = validator("name")(build_validate_func("foo"))  # name must be foo
```

From the example/a quick peak into the inner workings of `validator` I thought `validator` I thought it wasn't necessary to assign the method to the class itself, but I guess it is (which makes sense really).

**Comment by adriangb** [comment]
As a followup, to set a validator outside of the class definition, the easiest way I found is to inherit and overwrite the original class:
```python3
class Bar(BaseModel):
    name: str

class Bar(Bar):

    validate_name = validator("name")(build_validate_func("bar"))  # name must be bar
```

If anyone has a better idea, I'd love to hear it!
